### PR TITLE
fix: refresh wallet list after tx

### LINKED ISSUE #2210: [Bug] After complete the transfer token within Mask wallet; balance did not refresh
## Bug Report

E.g.  I transfered some token from Mask wallet to some addr. (wallet connected to MetaMask).

After the tx is recorded;
- when pending - No UX indicating its pending;
- After confirmed by eth (like etherscan); The Balance of that token is not updated. Need manual refresh

### System

- [ ] Windows

  - OS Version:

- [ ] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome

  - Mask Version:
  - Browser Version:

- [x] Firefox

  - Mask Version:
  - Browser Version:

- [ ] Android

  - Mask Version:
  - Android Version:

- [ ] iOS
  - Mask Version:
  - iOS Version:

### Build Variant

- Where do you get Mask?
  - [ ] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

/_What happened?_/

### PR DESCRIPTION
**Pull request by zhouhanseng**
close #2210

### CODE REVIEW

File: packages/maskbook/src/extension/options-page/DashboardRouters/Wallets.tsx [hunk 1]
```diff
@@ -84,6 +85,11 @@ const useStyles = makeStyles((theme) =>
     }),
 )
 
+export const DashboardWalletsContext = createContext<{
```
Comment (zhouhanseng) [inline packages/maskbook/src/extension/options-page/DashboardRouters/Wallets.tsx:88]: Add context here in `Wallets.tsx` rather than integrate context with  `useAssetsDetailedCallback.ts`, since only in this component props need to be passed through too many components.

File: packages/maskbook/src/extension/options-page/DashboardComponents/TransferDialog.tsx [hunk 2]
```diff
@@ -108,18 +110,10 @@ function TransferTab(props: TransferTabProps) {
...
             if (transferState.type !== TransactionStateType.CONFIRMED) return
-
-            // reset form
-            setAmount('')
-            setAddress('')
-            setMemo('')
-
-            // revalidate
+            onClose()
+            retryDetailedTokens()
```
Comment (zhouhanseng) [inline packages/maskbook/src/extension/options-page/DashboardComponents/TransferDialog.tsx:116]: retry fetch https://api.debank.com/token/balance_list after tx.

File: packages/maskbook/src/extension/options-page/DashboardComponents/TransferDialog.tsx [hunk 3]
```diff
@@ -108,18 +110,10 @@ function TransferTab(props: TransferTabProps) {
...
-
             if (transferState.type !== TransactionStateType.CONFIRMED) return
-
-            // reset form
-            setAmount('')
-            setAddress('')
-            setMemo('')
-
-            // revalidate
+            onClose()
```
Comment (guanbinrui) [inline packages/maskbook/src/extension/options-page/DashboardComponents/TransferDialog.tsx:115]: Why prefers to close the dialog rather than reset it?

File: packages/maskbook/src/extension/options-page/DashboardRouters/Wallets.tsx [hunk 4]
```diff
@@ -84,6 +85,11 @@ const useStyles = makeStyles((theme) =>
...
+    detailedTokens: AssetDetailed[]
+    retryDetailedTokens: () => void
+}>(null!)
```
Comment (guanbinrui) [inline packages/maskbook/src/extension/options-page/DashboardRouters/Wallets.tsx:91]: Dose it necessary to give an empty implementation here?

File: packages/maskbook/src/extension/options-page/DashboardComponents/TransferDialog.tsx (hunk 3 above)
Comment (zhouhanseng) [reply packages/maskbook/src/extension/options-page/DashboardComponents/TransferDialog.tsx:115]: No, it will be reset after close the dialog.

File: packages/maskbook/src/extension/options-page/DashboardRouters/Wallets.tsx (hunk 4 above)
Comment (zhouhanseng) [reply packages/maskbook/src/extension/options-page/DashboardRouters/Wallets.tsx:91]: I think it's okay to use `null!` since it will be initialized here: https://github.com/DimensionDev/Maskbook/pull/2216/files#diff-ebc6683e3022ce8a049715586713e2d796eae531aa5b5e96692e98762a355d41R155

**Review by guanbinrui — APPROVED** [review]
