### PR TITLE
[Release] Hotfix 1.19.5 (patch) 

### LINKED ISSUE #1770: [Bug] Add WalletConnect connection status
# Bug Report

### System

- [ ] Windows

  - OS Version:

- [x] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome

  - Maskbook Version:
  - Browser Version:

- [ ] Firefox

  - Maskbook Version:
  - Browser Version:

- [ ] Android

  - Maskbook Version:
  - Android Version:

- [ ] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

## Bug Info

Screen Shot 2020-10-22 at 21 42 33

### Actual Behavior

/_What happened?_/

### LINKED ISSUE #1865: [Bug] Fail to decode red packet payload on mobile on twitter
# Bug Report

### System

- [ ] Windows

  - OS Version:

- [ ] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [ ] Chrome

  - Maskbook Version:
  - Browser Version:

- [ ] Firefox

  - Maskbook Version:
  - Browser Version:

- [ ] Android

  - Maskbook Version:
  - Android Version:

- [x] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook?
  - [ ] Store
  - [x] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

## Bug Info
This issue is not reproducible on previous version (1.18.2)

Create a redpacket on rinkeby, then check the post, there is error message with "Maskbook has an error" as below screenshot.

1. Send redpackets from mobile app or Chrome/Firefox, on **Chrome/Firefox** everything works properly
2. Send redpackets from mobile app or Chrome/Firefox, on **mobile** the issue occurs at 100%.

So this issue should be related to the redpacket plugin view injection on the mobile app Twitter.

### Actual Behavior

/_What happened?_/
Simulator Screen Shot - iPhone 12 Pro Max - 2020-11-09 at 09 28 42

### LINKED ISSUE #1866: [Bug] Version absence on the about dialog
# Bug Report

### System

- [ ] Windows

  - OS Version:

- [x] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome

  - Maskbook Version:
  - Browser Version:

- [ ] Firefox

  - Maskbook Version:
  - Browser Version:

- [ ] Android

  - Maskbook Version:
  - Android Version:

- [ ] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

test

### PR DESCRIPTION
**Pull request by guanbinrui**
close #1865
close #1866

### CODE REVIEW

File: packages/maskbook/src/extension/options-page/DashboardDialogs/About.tsx [hunk 1]
```diff
@@ -72,15 +72,19 @@ const useStyles = makeStyles((theme) =>
...
+    const version = globalThis.browser?.runtime.getManifest()?.version ?? process.env.TAG_NAME.slice(1)
     return (
         <DashboardDialogCore {...props} CloseIconProps={{ className: classes.close }}>
             <section className={classes.wrapper}>
                 <header className={classes.header}>
                     <Avatar className={classes.maskface} src="/MB--CircleCanvas--WhiteOverBlue.svg"></Avatar>
                     <img className={classes.masktext} src="/maskbook-title-white.svg" />
                     <Typography className={classes.version} variant="body2" color="inherit">
-                        {t('version_of_stable', { version })}
+                        {t(process.env.build === 'stable' ? 'version_of_stable' : 'version_of_unstable', {
```
Comment (Jack-Works) [inline packages/maskbook/src/extension/options-page/DashboardDialogs/About.tsx:83]: Can our i18n analyze tool analyze this pattern? @septs

Comment (septs) [reply packages/maskbook/src/extension/options-page/DashboardDialogs/About.tsx:83]: https://github.com/DimensionDev/Maskbook/blob/c7e25c5ead7c13c3d301d4eb028d589b91143859/scripts/locale-kit.ts#L90-L92

Comment (guanbinrui) [reply packages/maskbook/src/extension/options-page/DashboardDialogs/About.tsx:83]: Those part have been moved to #1875.
