### PR TITLE
fix: incorrect numeric format in tradeview

### LINKED ISSUE #3392: [Bug] Incorrect numeric format in tradeview
### How to reproduce?
Screen Shot 2021-06-16 at 19 46 09

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

### PR DESCRIPTION
**Pull request by NikoManiac**
closes #3392

### CODE REVIEW

**Review by nuanyang233 — APPROVED** [review]

File: packages/shared/src/wallet/formatter.tsx [hunk 1]
```diff
@@ -48,7 +48,7 @@ export function formatBalance(rawValue: BigNumber.Value = '0', decimals = 0, sig
 export function formatCurrency(value: BigNumber.Value, sign = '') {
     const balance = new BigNumber(value)
     const fixedBalance = balance.gt(1) ? balance.toFixed(2) : balance.toPrecision(2)
-    return `${sign}${fixedBalance.replace(/\d(?=(\d{3})+\.)/g, `${sign}&,`)}`
+    return `${sign}${fixedBalance.replace(/\d(?=(\d{3})+\.)/g, '$&,')}`
```
Comment (septs) [inline packages/shared/src/wallet/formatter.tsx:51]: the function need unit test.

Comment (guanbinrui) [reply packages/shared/src/wallet/formatter.tsx:51]: All test cases were down. Need rise an issue for it.

**Review by guanbinrui — APPROVED** [review]
