### PR TITLE
fix: improve toolbox in Twitter

### LINKED ISSUE #2671: [Bug] Improve toolbox on Twitter
### System

- [ ] Windows

  - OS Version:

- [x] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome

  - Mask Version:
  - Browser Version:

- [ ] Firefox

  - Mask Version:
  - Browser Version:

- [ ] Android

  - Mask Version:
  - Android Version:

- [ ] iOS
  - Mask Version:
  - iOS Version:

### Build Variant

- Where do you get Mask?
  - [ ] Store
  - [ ] ZIP
  - [x] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

+ Rename the injected menu item to "Mask Network".
+ The gap above the injected menu item does not follow the original ones.
+ The height of the injected menu item is a litter bigger than the original ones.
+ The popper over should follow the original style (font, box-shadow, etc.).
+ The smiley face logo is smaller than other icons in the menu list.

image

Here is the injected toolbox popper over:

image

Here is the original popper over:

image

### PR DESCRIPTION
**Pull request by lelenei**
close #2671

### CODE REVIEW

File: packages/maskbook/src/components/InjectedComponents/ToolboxHint.tsx [hunk 1]
```diff
@@ -133,31 +146,43 @@ export function ToolboxHint() {
     const [menu, openMenu] = useMenu(
         <>
             <MenuItem onClick={openEncryptedMessage}>
```
Comment (Jack-Works) [inline packages/maskbook/src/components/InjectedComponents/ToolboxHint.tsx:148]: Why not add `classes.menuItem` on the `MenuItem` tag?

**Review by Jack-Works — DISMISSED** [review]

**Review by Jack-Works — DISMISSED** [review]

**Review by Jack-Works — DISMISSED** [review]

**Review by Jack-Works — DISMISSED** [review]

**Comment by Jack-Works** [comment]
@lelenei I mark this as draft for now. feel free to mark it as ready

**Review by guanbinrui — APPROVED** [review]

**Review by Jack-Works — APPROVED** [review]
