### PR TITLE
fix: harden fungibleTokenLink resolver

### LINKED ISSUE #7516: [Crash] Error: Path parameter address cannot be an empty string.
I tried to open token list in Tips dialog with Flow wallet, then Mask reports an error.

> Path parameter address cannot be an empty string.

Error stack:

<pre>Error: Path parameter address cannot be an empty string.
  at chrome-extension://ifiapmffifjaablbakghjgfhjfphlooi/js/6679.js:44544:19
  at [Symbol.replace] (<anonymous>)
  at String.replace (<anonymous>)
  at path (chrome-extension://ifiapmffifjaablbakghjgfhjfphlooi/js/6679.js:44531:33)
  at urlcatImpl (chrome-extension://ifiapmffifjaablbakghjgfhjfphlooi/js/6679.js:44484:14)
  at urlcat (chrome-extension://ifiapmffifjaablbakghjgfhjfphlooi/js/6679.js:44474:16)
  at Object.fungibleTokenLink (chrome-extension://ifiapmffifjaablbakghjgfhjfphlooi/js/5881.js:490:108)
  at chrome-extension://ifiapmffifjaablbakghjgfhjfphlooi/js/1455.js:330:45
  at Object.useMemo (chrome-extension://ifiapmffifjaablbakghjgfhjfphlooi/js/npm.react-dom.js:393:189)
  at exports.useMemo (chrome-extension://ifiapmffifjaablbakghjgfhjfphlooi/js/1455.js:1169:208)</pre>

## Build info
- Version: 2.13.1
- NODE_ENV: production
- target: chromium
- build: beta
- architecture: web
- BUILD_DATE: 2022-09-27T08:38:51.784Z
- VERSION: undefined-reproducible

## Git ():

N/A (N/A)
N/A

### PR DESCRIPTION
**Pull request by UncleBill**
https://mask.atlassian.net/browse/MF-2235
closes https://github.com/DimensionDev/Maskbook/issues/7516

### CODE REVIEW

**Review by guanbinrui — DISMISSED** [review]

File: packages/web3-shared/base/src/utils/resolver.ts [hunk 1]
```diff
@@ -125,11 +125,13 @@ export function createExplorerResolver<ChainId, SchemaType, NetworkType>(
                 domain,
                 ...getExplorerURL(chainId)?.parameters,
             }),
-        fungibleTokenLink: (chainId: ChainId, address: string) =>
-            urlcat(getExplorerURL(chainId).url, fungibleTokenPathname, {
+        fungibleTokenLink: (chainId: ChainId, address: string) => {
+            if (!chainId || !address) return ''
```
Comment (guanbinrui) [inline packages/web3-shared/base/src/utils/resolver.ts]: It doesn't make sense. Why even `chainId` could be not given?

Comment (UncleBill) [reply packages/web3-shared/base/src/utils/resolver.ts]: In https://github.com/DimensionDev/Maskbook/issues/7516 , the address is empty string. But failed to reproduce it.

Comment (guanbinrui) [reply packages/web3-shared/base/src/utils/resolver.ts]: I see it claimed that: `Error: Path parameter address cannot be an empty string.` Not caused by `chainId`, right?

**Review by guanbinrui — APPROVED** [review]
