### PR TITLE
[Release] New release 1.37.0 (minor) 

### LINKED ISSUE #4043: [Bug] Encounter infinity initializing when switch network with Metamask - occasional problems
### How to reproduce?

1. Switch network with Metamask

### What happened?
The switch confirmation window will not pop up.
Screen Shot 2021-08-20 at 11 26 06

Workaround: Disable and re-enable mask plugin, then try to switch network, it should work again. 

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

### PR DESCRIPTION
**Pull request by guanbinrui**
closes #4043

### CODE REVIEW

File: packages/maskbook/src/extension/background-script/EthereumServices/providers/MetaMask.ts [hunk 1]
```diff
@@ -32,35 +32,35 @@ async function onChainIdChanged(id: string) {
...
-    await resetAccount({
-        providerType: ProviderType.MetaMask,
-    })
-}
-
-export function createProvider() {
-    if (provider) return provider
+export async function createProvider() {
+    // @ts-ignore
+    if (provider && provider.chainId !== null) return provider
```
Comment (Jack-Works) [inline packages/maskbook/src/extension/background-script/EthereumServices/providers/MetaMask.ts:37]: This error comes from ESLint
