### PR TITLE
fix: the entrance of PL

### LINKED ISSUE #3742: [Bug] PoolTogether Plugin adds switch button on unsupported networks.
### How to reproduce?

1.Go to this tweet included PoolTogether plugin: https://twitter.com/WEN6666661/status/1417773984716787718
2.Change to the networks other than eth or matic;
3.Check the plugin card.

### What happened?
Plugin card was showing "There is no pool on this network."

### What should happen?
Provide the switch to Eth button for unsupported networks likes other plugins.
### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [x] Build of version/commit hash: develop

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

### PR DESCRIPTION
**Pull request by guanbinrui**
closes #3742

### CODE REVIEW

File: packages/maskbook/src/plugins/PoolTogether/SNSAdaptor/index.tsx [hunk 1]
```diff
@@ -44,7 +46,11 @@ function Renderer(props: React.PropsWithChildren<{ url: string }>) {
     return (
         <MaskbookPluginWrapper pluginName="PoolTogether">
             <Suspense fallback={<SnackbarContent message="Mask is loading this plugin..." />}>
-                <PoolTogetherView />
+                <EthereumChainBoundary
+                    chainId={ChainId.Mainnet}
+                    isValidChainId={(chainId) => [ChainId.Mainnet, ChainId.Matic].includes(chainId)}>
```
Comment (septs) [inline packages/maskbook/src/plugins/PoolTogether/SNSAdaptor/index.tsx:51]: this field allow input array may be a better

```suggestion
                    isValidChainId={[ChainId.Mainnet, ChainId.Matic]}>
```

Comment (guanbinrui) [reply packages/maskbook/src/plugins/PoolTogether/SNSAdaptor/index.tsx:51]: A function parameter makes it able to express more complex logic.

**Review by septs — APPROVED** [review]
