### PR TITLE
fix: the settings dialog

### LINKED ISSUE #3973: [Crash] Doesn't select exchange automatically
1. I wanted to select slippage more than 5% as usually most of BSC tokens need higher slippage but Mask Swap feature currently doesn't allow to set Slippage more than 5%. Slider only goes from 0.5-5%
2. I had tokens selected for swap, I opened Swap setting window and clicked on Reset button. Which reset slippage to 0.5% but at the same time it deselected pancakeswap exchange from Supported by dropdown and set to blank. I have to set it manually. But it is difficult to know what happened as supported by exchange dropdown is usually not visible and I have to search for quite some time what happened to find the solution. I am reporting it just so other users don't face same issue when it is fixed.

## Build info
- Version: 1.35.2
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-08-10T08:03:20.001Z
- VERSION: v1.29.12-735-g7cf5dd33b

## Git ():

7cf5dd33b (released) on tag "v1.35.2"
git@github.com:DimensionDev/Maskbook.git

### PR DESCRIPTION
**Pull request by guanbinrui**
closes #3973

### CODE REVIEW

**Review by UncleBill — DISMISSED** [review]

File: packages/maskbook/src/plugins/Trader/SNSAdaptor/trader/SettingsDialog.tsx [hunk 1]
```diff
@@ -58,14 +60,14 @@ export function SettingsDialog(props: SettingsDialogProps) {
 
     const provider = useValueRef(currentTradeProviderSettings)
     const slippage = useValueRef(currentSlippageSettings)
+    const SHO = useValueRef(currentSingleHopOnlySettings)
```
Comment (septs) [inline packages/maskbook/src/plugins/Trader/SNSAdaptor/trader/SettingsDialog.tsx:63]: plz improve the variable name readability, e.g: `hopOnly`.

**Review by septs — APPROVED** [review]
