### PR TITLE
fix: peer to peer encryption

### LINKED ISSUE #3691: [Bug] “Share to” not worked as expected
### How to reproduce?

1. User A post a twitter, and select recipients only "myself"
2. User A append recipients to share it to User B.
3. User B view the twitter.
image

### What happened?
User B can't view the content of the twitter, it's always retrieving the post key.

### What should happen?
User B should be able to view the content, and the others can't view the content.

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

### PR DESCRIPTION
**Pull request by Jack-Works**
- chore: load gun worker fix early
- refactor: split pure shared out

closes #3691

### CODE REVIEW

**Review by Himself65 — APPROVED** [review]

File: packages/shared/src/index.ts [hunk 1]
```diff
@@ -1,17 +1,6 @@
...
-export * from './TypedMessage'
-export * from './utils'
 export * from './hooks'
-export * from './crypto/JWKType'
 export * from './wallet'
-export * from './Persona/type'
-export * from './Persona/type'
 export * from './UI'
 export * from './locales'
+export * from '@masknet/shared-base'
```
Comment (septs) [inline packages/shared/src/index.ts:6]: why?

**Review by guanbinrui — APPROVED** [review]
