### PR TITLE
fix: transak should only support Ethereum cryptocurrencies #2189

### LINKED ISSUE #2189: [Bug] Transak should only support Ethereum network (ETH/erc20) cryptocurrencies
### System

- [ ] Windows

  - OS Version:

- [x] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome

  - Maskbook Version:
  - Browser Version:

- [x] Firefox

  - Maskbook Version:
  - Browser Version:

- [ ] Android

  - Maskbook Version:
  - Android Version:

- [ ] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

We don't have any other non-Ethereum wallet built-in now. And we should not display the **Buy Now** on any non-Ethereum cryptocurrencies. Hide the **Buy Now** button if preview on non-Ethereum cryptocurrencies.

test

test

### PR DESCRIPTION
**Pull request by lelenei**
close #2189

### CODE REVIEW

File: packages/maskbook/src/plugins/Transak/hooks/useTransakAllowanceCoin.ts [hunk 1]
```diff
@@ -1,19 +1,21 @@
...
+import { CONSTANTS } from '../../../web3/constants'
+import { useConstant } from '../../../web3/hooks/useConstant'
+import {
+    TokenListsState,
+    useERC20TokensDetailedFromTokenLists,
+} from '../../../web3/hooks/useERC20TokensDetailedFromTokenLists'
+import { useEtherTokenDetailed } from '../../../web3/hooks/useEtherTokenDetailed'
 import type { Coin } from '../../Trader/types/trending'
 
-const ENV = {
```
Comment (septs) [inline packages/maskbook/src/plugins/Transak/hooks/useTransakAllowanceCoin.ts:4]: why remove remote data source?

File: packages/maskbook/src/plugins/Transak/hooks/useTransakAllowanceCoin.ts [hunk 2]
```diff
@@ -11,9 +11,12 @@ const URL = ENV[process.env.NODE_ENV]
...
 export function useTransakAllowanceCoin(coin: Coin): boolean {
     return useAsync(async () => {
-        const allowanceList = await fetch(URL, { method: 'GET' })
-            .then((res) => res.json())
-            .then((res) => res.response)
-        return allowanceList.map((val: Coin) => val.symbol).includes(coin.symbol)
+        if (coin.eth_address || coin.symbol.toLowerCase() === 'eth') {
+            const allowanceList = await fetch(URL, { method: 'GET' })
+                .then((res) => res.json())
+                .then((res) => res.response)
```
Comment (septs) [inline packages/maskbook/src/plugins/Transak/hooks/useTransakAllowanceCoin.ts:17]:
```suggestion
            const response = await fetch(URL, { method: 'GET' })
            const payload: { response: Coin[] } = await response.json()
            const allowanceList = payload.response
```

**Review by Jack-Works — APPROVED** [review]

**Review by guanbinrui — APPROVED** [review]
