### PR TITLE
fix: add back menu button in mobile app

### LINKED ISSUE #2388: [Bug] Mobile App Dashboard Wallet page misses the more menu button
### System

- [ ] Windows

  - OS Version:

- [ ] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [ ] Chrome

  - Mask Version:
  - Browser Version:

- [ ] Firefox

  - Mask Version:
  - Browser Version:

- [ ] Android

  - Mask Version:
  - Android Version:

- [ ] iOS
  - Mask Version:1.27.4
  - iOS Version:1.27.3

### Build Variant

- Where do you get Mask?
  - [x] Store
  - [x] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

## Bug Info
On Mask Network mobile app, in the Dashboard -> Wallet page, there is no menu button for users to backup/delete current wallet

### Actual Behavior

/_What happened?_/

### PR DESCRIPTION
**Pull request by jk234ert**
fix #2388

### CODE REVIEW

File: packages/maskbook/src/extension/options-page/DashboardComponents/WalletContent.tsx [hunk 1]
```diff
@@ -143,43 +143,41 @@ export const WalletContent = forwardRef<HTMLDivElement, WalletContentProps>(func
...
+                                setBuyDialogOpen({
+                                    open: true,
+                                    address: wallet.address,
+                                })
+                            }}
+                            startIcon={<MonetizationOnOutlinedIcon />}>
+                            {t('buy_now')}
+                        </Button>
+                    ) : null}
+                    <IconButton
```
Comment (jk234ert) [inline packages/maskbook/src/extension/options-page/DashboardComponents/WalletContent.tsx:173]: The change is pretty simple:
Leave <IconButton> always visible since it contains the menu button, which should always be there.
Then add `xsMatched` check into every other components

**Review by Jack-Works — APPROVED** [review]

**Review by guanbinrui — APPROVED** [review]
