### PR TITLE
fix: hint info in wallet creation dialog being covered by the activated confirm button

### LINKED ISSUE #2826: [Bug] [UI] tip info in wallet creation dialog covered by the activated confirm button.
### How to reproduce?

1. Select wallet tab in dashboard
2. Click "create wallet" to create a walet
3. Select the checkbox then click on the tip icon.

### What happened?

image

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

### PR DESCRIPTION
**Pull request by UncleBill**
update some style as well after communicating with @xiazhiming 

closes #2826

| | |
|--|--|
| image | image |
| image | image |

### CODE REVIEW

File: packages/maskbook/src/extension/options-page/DashboardDialogs/Wallet.tsx [hunk 1]
```diff
@@ -153,18 +153,20 @@ const useWalletImportDialogStyle = makeStyles((theme: Theme) =>
             fontSize: 12,
             fontWeight: 500,
             textAlign: 'center',
-            backgroundColor: '#FFD5B3',
+            backgroundColor: '#EFF5FF',
             color: 'black',
             padding: '8px 22px',
-            margin: '24px -36px 0',
+            margin: '8px 0 0',
```
Comment (nuanyang233) [inline packages/maskbook/src/extension/options-page/DashboardDialogs/Wallet.tsx:159]: How about `marginTop: theme.spacing(1)`

**Review by Jack-Works — APPROVED** [review]

**Review by guanbinrui — APPROVED** [review]
