### PR TITLE
[Release] New release 2.7.0 (minor)

### LINKED ISSUE #6001: [BUG]plugin code generate
## Bug Info
when I use `npx gulp new-pkg` to generate a new plugin file, code added to `config.ts` was wrong
### How to reproduce?
enter command `npx gulp new-pkg` to generate a plugin

### What happened?
the path of plugin is 
```
 join(__dirname, '../../packages/plugins/ENS/src')
```

image

### What should happen?
the path of plugin should be
```
join(__dirname, '../../plugins/ENS/src')
```
### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

### LINKED ISSUE #6082: [Demand] ：add public key of persona from plugin context
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background
I need public key of current persona like
```
  const currentPersona = {
        nickname: 'Ran11',
        identifier: {
            curve: 'secp256k1',
            compressedPoint: 'ApAfUsdGNQ5NKtii6b+j+8GMvsm4KrgbhNDnUfjXugU5',
            type: 'ec_key',
        },
        publicHexKey: '0x02901f52c746350e4d2ad8a2e9bfa3fbc18cbec9b82ab81b84d0e751f8d7ba0539',
    }
```
## Part 2: Problem to Solve
add publicHexKey in persona

### LINKED ISSUE #6100: [Bug] Decrypted by Mask doesn’t work, Mask Network (dev) 2.6.0
### How to reproduce?

1. Go to some plugin
2. Create and post encrypted tweet
3. Go to tweet

### What happened
Decrypted by Mask doesn’t work, tweet's content doesn’t unavailable although Mask is installed.

### What should happen?
User should see Decrypted by Mask tweet.

## Environment
Dev environment, last version of develop branch, commit: https://github.com/DimensionDev/Maskbook/commit/e49cd5c0e54339ef602de598be62f7eb28ad7407

Screenshot 2022-04-18 at 11 14 46

### Mask Version:
- [ ] (Browser) Chrome Version 100.0.4896.75
- [ ] (Mask App) Installed from the local build. (`/dist`)
- [ ] Develop branch
- [ ] Build of version/commit hash: commit hash: e49cd5c0e54339ef602de598be62f7eb28ad7407

### System
- [ ] Mac OS X Catalina

### Platform/Browser

- [ ] Chrome Version 100.0.4896.75

https://user-images.githubusercontent.com/32291396/163794513-bcd41010-3d62-44d6-9a3a-1eb679143d03.mov

Screenshot 2022-04-18 at 11 15 04
Screenshot 2022-04-18 at 11 15 21

Screenshot 2022-04-18 at 11 14 46

### PR DESCRIPTION
**Pull request by guanbinrui**
✔ No breaking changes.

🆕 New Feature

*  feat!: optimize payload size of payload v37 (#5908)
*  feat(twitter): upload avatar api (#6000)
*  feat: Go Plus Security plugin (#5873)
*  feat: aave v2 (#5651)
*  feat: add 3 api to plugin context (#6064)
*  feat: add <ConcealableTabs /> (#6073)
*  feat: add ECKeyIdentifier.publicKeyAsHex close GH-6082 (#6085)
*  feat: add cross-chain-bridge plugin (#6016)
*  feat: add new cli fix lockfile
*  feat: add token security rules (#6039)
*  feat: add transaction dialog in saving plugin (#6076)
*  feat: check contract address (#5969)
*  feat: configurable app board (#5939)
*  feat: create next kv server api (#5994)
*  feat: domain name service (#5931)
*  feat: enable es2021 syntax (#6027)
*  feat: go pocket feedback (#6014)
*  feat: improve mask popup (#5986)
*  feat: introduce ses in dev (#5759)
*  feat: manage recent pending transactions (#6055)
*  feat: new app board (#6018)
*  feat: new intial persona page (#6122)
*  feat: persona QR code (#5990)
*  feat: tip NFT (#6013)
*  feat: tips entrance (#6012)

🎨 UI Improvements

🐛 Bug Fixes

*  fix(instagram): can't open web3 tab (#6011)
*  fix(kv): fetch with no-cors mode response opaque data (#5940)
*  fix(mobile): no media viewer (#5925)
*  fix(share): popup share (#6003)
*  fix(tip): adjust size of the badge of WalletIcon (#6044)
*  fix(tip): ajust size of tip button according to twitter's (#5970)
*  fix(tip): change promote text in share message (#5984)
*  fix(tip): hide tip button when evm is not actived (#5982)
*  fix(tip): set significant to 6 for formatting max amount (#6062)
*  fix(tip): styling tip button in post (#5981)
*  fix(twitter): search injected dom selector (#5944)
*  fix(zora): check ipfs before resolving
*  fix(zora): check ipfs before resolving (#5949)
*  fix: ITO history default icon (#6078)
*  fix: add ellipsis effect for nft contract name (#6041)
*  fix: add token type check for token list (#6033)
*  fix: adjust maskicon position (#5943)
*  fix: app board wallet disconnected display (#6007)
*  fix: bsc to bnb (#5965)
*  fix: bugfix for next id (#5934)
*  fix: can't auto close dialog when lost focus (#5977)
*  fix: downgrade react-refresh
*  fix: duplicate render by unique key (#6123)
*  fix: file service not show close #6100
*  fix: hidden web3 tab page (#6021)
*  fix: hyper proxy r2d2 route not work on cloudflare (#5955)
*  fix: icon position in minds.com (#5899)
*  fix: if gulp biuld-ci fails, ci should fail as well (#6107)
*  fix: if phantom is locked, might not able to open its popup (#6115)
*  fix: improve input fields (#5996)
*  fix: improve loading in collectible offers and order table (#5987)
*  fix: incorrect contracts query on dashboard (#6095)
*  fix: incorrect plugin name (#6077)
*  fix: incorrect text (#6096)
*  fix: ito entrance (#5968)
*  fix: jsx-key (#6074)
*  fix: line break (#5950)
*  fix: lint errors about docs (#5953)
*  fix: lost default network indicator (#5976)
*  fix: lucky drop schema (#6093)
*  fix: lucky drop send from past use image payload (#5992)
*  fix: missing builds (#5935)
*  fix: mnemonic words exports (#6136)
*  fix: new-pkg command close GH-6001
*  fix: next id bugs (#5936)
*  fix: persona db overwrite bug (#5964 #5966)
*  fix: persona not preview in full page when printing (#6043)
*  fix: plugin wrapper (#5947)
*  fix: reduce jsx nested (#6124)
*  fix: reduce token list rerenders (#6036)
*  fix: reply review (#5946)
*  fix: revert constants (#5957)
*  fix: select user missing
*  fix: should filter asset which not on support chain (#6050)
*  fix: should update tip status when next id verify status changed (#6020)
*  fix: sns share in ITO and PET (#5941)
*  fix: sprint2 ui issues  (#6042)
*  fix: support translate css (#5800)
*  fix: twitter image (#5967)
*  fix: twitter nickname selector (#6006)
*  fix: type error (#6113)
*  fix: typos (#5948)
*  fix: ui style (#6051)
*  fix: web3 tab lose focus (#5988)
*  fix: zora api (#5942)

👩‍💻 Miscellaneous

*  chore: add .github/security.md file (#6060)
*  chore: add back conflux constants (#5999)
*  chore: add conflux config (#6112)
*  chore: add cross isolation message (#5961)
*  chore: add security report section (#6058)
*  chore: change iOS idb fix
*  chore: clean bool state variable name (#5975)
*  chore: improve backup info card (#6063)
*  chore: improve code style (#6090)
*  chore: improve eslint (#6084)
*  chore: improve purchase dialog (#6010)
*  chore: patch @solana/web3.js (#6125)
*  chore: pick some small changes from ses branch (#6038)
*  chore: remove flag (#5960)
*  chore: remove package alias in webpack config (#6054)
*  chore: replace webcrypto liner (#6069)
*  chore: setup i18n in background (#6086)
*  chore: simplify use callback (#6046)
*  chore: stronger settings type (#6005)
*  chore: temp disable lockdown on firefox
*  chore: turn on fortmatic (#6127)
*  chore: update plugin template
*  chore: upgrade @types/react to react 18 (#6053)
*  chore: upgrade android target version to 99
*  chore: upgrade web3 (#6025)
*  docs: improve documentation (#5883)
*  refactor: avoid prop drilling (#6083)
*  refactor: cleanup post context (#6089)
*  refactor: ito card footer button (#5985)
*  refactor: migrate PersonaHome for SSR (#5995)
*  refactor: move 2 settings and improve mv3
*  refactor: move @masknet/typed-message package to esm (#6070)
*  refactor: move MAX_PERSONA_LIMIT and formatPersonaFingerprint
*  refactor: move MaskThemeProvider (#5993)
*  refactor: move app_only_queryPersonas
*  refactor: move attach/detach profile
*  refactor: move backup code to backup-format package (#5922)
*  refactor: move backupPersonaPrivateKey
*  refactor: move createPersonaByMnemonicV2 and renamePersona
*  refactor: move debugger settings (#6026)
*  refactor: move detachProfileWithNextID
*  refactor: move downloadBackup
*  refactor: move getPersonaAvatar and updatePersonaAvatar
*  refactor: move i18next instance to shared-base (#6004)
*  refactor: move mobile_restoreFromMnemonicWords
*  refactor: move openDashboard
*  refactor: move queryLastPersonaCreated
*  refactor: move queryOwnedPersonaInformation
*  refactor: move queryPagedPostHistory
*  refactor: move queryPersonaByMnemonic
*  refactor: move queryPersonaByPrivateKey
*  refactor: move queryRelationPaged
*  refactor: move relation methods
*  refactor: move resolveUnknownLegacyIdentity
*  refactor: move some functions
*  refactor: move tips ui from NextID to Tips (#6121)
*  refactor: move typed-message tests (#6137)
*  refactor: open window (#5972 #5974)
*  refactor: pick theme refactor from GH-6009 (#6023)
*  refactor: recover cfx constants (#6030)
*  refactor: reduce rerender times (#5998)
*  refactor: reduce rerendering (#5952)
*  refactor: remove hash router (#6141)
*  refactor: remove unused field pluginDefine.icon (#6024)
*  refactor: remove unused plugin entries
*  refactor: remove unused queryProfilesPagedDB
*  refactor: remove unused web api for native
*  refactor: rename WelcomeService to BackupService
*  refactor: rename createSubscriptionFromValueRef
*  refactor: reorgnize theme package (#6059)
*  refactor: shared message bus (#5971)
*  refactor: split plugin infra entries (#6057)
*  refactor: turn token picking into async call (#5632)

### CODE REVIEW

File: packages/backup-format/src/utils/hex2buffer.ts [hunk 1]
```diff
@@ -0,0 +1,36 @@
+/** @internal */
+export function hex2buffer(hexString: string, padded?: boolean) {
```
Comment (septs) [inline packages/backup-format/src/utils/hex2buffer.ts]: move to `@dimensiondev/kit`?
