### PR TITLE
fix: pre-build does not fail on ci

### LINKED ISSUE #2729: [Bug] Fix build failed exit code incorrect
see https://github.com/DimensionDev/Maskbook/actions/runs/704979223
see https://github.com/DimensionDev/Maskbook/actions/runs/704979228

image

even if the compile failed, CI think it all pass.

### PR DESCRIPTION
**Pull request by Jack-Works**
close #2729

### CODE REVIEW

File: packages/cli/build/dev.ts [hunk 1]
```diff
@@ -7,7 +7,7 @@ import { noop } from 'lodash'
 import { isLocked } from './process-lock'
 
 async function main() {
-    if (!isLocked()) await build()
+    if (!isLocked()) await build().catch(() => {})
```
Comment (septs) [inline packages/cli/build/dev.ts:10]:
```suggestion
    if (!isLocked()) await build().catch(noop)
```

**Review by septs — DISMISSED** [review]
