### PR TITLE
fix: hide the expand button if nothing to view in expanded mode 

### LINKED ISSUE #2673: [Bug] Hide the expand button if nothing to view in expanded mode
### System

- [ ] Windows

  - OS Version:

- [x] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome

  - Mask Version:
  - Browser Version:

- [ ] Firefox

  - Mask Version:
  - Browser Version:

- [ ] Android

  - Mask Version:
  - Android Version:

- [ ] iOS
  - Mask Version:
  - iOS Version:

### Build Variant

- Where do you get Mask?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

image

### PR DESCRIPTION
**Pull request by lelenei**
close #2673

### CODE REVIEW

**Comment by Jack-Works** [comment]
Need one approval from @guanbinrui or @zhouhanseng

**Comment by guanbinrui** [comment]
> #2673

Hi @lelenei  Please take a view on this.

https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

File: packages/maskbook/src/extension/options-page/DashboardComponents/WalletAssetsTable.tsx [hunk 1]
```diff
@@ -336,12 +336,19 @@ export function WalletAssetsTable(props: WalletAssetsTableProps) {
                     </TableBody>
                 </Table>
             </TableContainer>
-            <LessButton
-                isMobile={isMobile}
-                setViewLength={setViewLength}
-                setPrice={setPrice}
-                detailedTokens={detailedTokens}
-            />
+            {detailedTokens.filter((x) =>
```
Comment (guanbinrui) [inline packages/maskbook/src/extension/options-page/DashboardComponents/WalletAssetsTable.tsx:339]: The token filtering logical was using twice. Please refactor it to only use once. A easy catch up solution is like:

```typescript
const visibleTokens = detailedTokens.filter(...)

// Then you can use visibleTokens directly, no need to filter detailedToken again.
```

**Review by guanbinrui — CHANGES_REQUESTED** [review]

**Review by guanbinrui — APPROVED** [review]
