### PR TITLE
fix: peopleList performance problem

### LINKED ISSUE #3634: [Bug] Unable to add receipt with huge contacts (more than 2k)
### How to reproduce?

1. Restore from the account with 2k contracts.
2. Publish a tweet with `only myself`
3. Click the `Add Receipt` button

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

### PR DESCRIPTION
**Pull request by nuanyang233**
close #3634 

This will cause the page to crash when users open the recipients' dialog with huge contacts data. So I added virtual lists and conditional rendering of ListItem.

## Before 

before

## After

after

### CODE REVIEW

File: packages/maskbook/src/components/shared/SelectPeopleAndGroups/PersonOrGroupInList.tsx [hunk 1]
```diff
@@ -37,62 +37,95 @@ const useStyle = makeStyles((theme: Theme) => ({
...
-        avatar = (
-            <MuiAvatar>
-                <GroupIcon />
-            </MuiAvatar>
+
+    if (isGroup(props.item))
+        return (
+            <ListItem button disabled={disabled} onClick={onClick} {...listItemProps}>
+                <GroupListItemContent group={props.item} showAtNetwork={showAtNetwork} />
+            </ListItem>
```
Comment (nuanyang233) [inline packages/maskbook/src/components/shared/SelectPeopleAndGroups/PersonOrGroupInList.tsx:49]: Let me explain here. Because GroupListItem needs to call `useNickNamesFromList` and `useResolveSpecialGroupName`. But there are time-consuming operations in these two hooks. But the reality is that there are not a lot of Groups. So I extract it to the `GroupListItemContent` component and added a conditional judgment to reduce unnecessary waste. 

image

**Comment by nuanyang233** [comment]
There was still a problem: when the user clicked **select all**, it would cause a crash. (Too many tags need to create)

Maybe we can change the design here. for example, **select all** just is an ALL tag, CC @xiazhiming @guanbinrui

**Review by Jack-Works — APPROVED** [review]

**Comment by nuanyang233** [comment]
> There was still a problem: when the user clicked **select all**, it would cause a crash. (Too many tags need to create)
> 
> Maybe we can change the design here. for example, **select all** just is an ALL tag, CC @xiazhiming @guanbinrui

I will replace the `select all` behavior to add an `All` tag.

File: packages/maskbook/src/extension/background-script/Jobs/DatabaseCleanup/CleanProfileAndAvatar.ts [hunk 2]
```diff
@@ -23,6 +26,7 @@ export async function cleanProfileWithNoLinkedPersona() {
     )
     const expired = new Date(Date.now() - 1000 * 60 * 60 * 24 * 14 /** days */)
     await consistentPersonaDBWriteAccess(async (t) => {
+        if (signal.aborted) throw new Error('')
```
Comment (guanbinrui) [inline packages/maskbook/src/extension/background-script/Jobs/DatabaseCleanup/CleanProfileAndAvatar.ts:29]:
```suggestion
        if (signal.aborted) throw new Error('Abort')
```

**Review by guanbinrui — APPROVED** [review]
