### PR TITLE
hide chain network change setting on mobile

### LINKED ISSUE #2353: [Bug] Remove `select eth mainnet` func on mobile (iOS) version
## Bug Report

This func is not needed for general users.

### System

- [ ] Windows

  - OS Version:

- [ ] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [ ] Chrome

  - Mask Version:
  - Browser Version:

- [ ] Firefox

  - Mask Version:
  - Browser Version:

- [ ] Android

  - Mask Version:
  - Android Version:

- [x] iOS
  - Mask Version:
  - iOS Version:

### Build Variant

- Where do you get Mask?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

/_What happened?_/

### PR DESCRIPTION
**Pull request by jk234ert**
close #2353

### CODE REVIEW

File: packages/maskbook/src/utils/flags.ts [hunk 1]
```diff
@@ -28,7 +28,7 @@ export const Flags = {
     /** Firefox has a special API that can inject to the document with a higher permission. */
     requires_injected_script_run_directly: process.env.target === 'firefox',
     // TODO: document why it enabled on app
-    support_eth_network_switch: appOnly || betaOrInsiderOnly,
```
Comment (Jack-Works) [inline packages/maskbook/src/utils/flags.ts:31]: remove the above comment too

**Review by Jack-Works — APPROVED** [review]
