### PR TITLE
fix: trending view keep loading without content

### LINKED ISSUE #2238: [Bug] trending view keep loading without content
### System

- [ ] Windows

  - OS Version:

- [x] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome

  - Mask Version:
  - Browser Version:

- [ ] Firefox

  - Mask Version:
  - Browser Version:

- [ ] Android

  - Mask Version:
  - Android Version:

- [ ] iOS
  - Mask Version:
  - iOS Version:

### Build Variant

- Where do you get Mask?
  - [ ] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

## Bug Info
https://twitter.com/search?q=%23sports&src=typed_query

### Actual Behavior

/_What happened?_/

### PR DESCRIPTION
**Pull request by zhouhanseng**
close #2238 The bug is due to there're some tokens which has data on DataProvider but nothing on chain. In this situation, we should fallback to use DataProvider.

fixed:

### CODE REVIEW

File: packages/maskbook/src/plugins/Trader/UI/trending/SearchResultView.tsx [hunk 1]
```diff
@@ -153,15 +156,9 @@ export function SearchResultView(props: SearchResultViewProps) {
     const canSwap = trending.coin.eth_address || trending.coin.symbol.toLowerCase() === 'eth'
     const swapTabIndex = dataProvider !== DataProvider.UNISWAP ? 3 : 1
     const fromToken = chainId === ChainId.Mainnet && coin.is_mirrored ? UST : createEtherToken(chainId)
-    const { decimals, name: tokenName, symbol } = coinDetailed ?? trending.coin
```
Comment (zhouhanseng) [inline packages/maskbook/src/plugins/Trader/UI/trending/SearchResultView.tsx]: decimals is the only thing we should use from coinDetailed since the name and symbol of coinDetailed is empty string.

image

image

File: packages/maskbook/src/plugins/Trader/UI/trending/SearchResultView.tsx [hunk 2]
```diff
@@ -154,14 +156,9 @@ export function SearchResultView(props: SearchResultViewProps) {
...
+    const { decimals } = coinDetailed ?? trending.coin
     const toToken = trending.coin.eth_address
-        ? createERC20Token(
-              chainId,
-              coinDetailed.address,
-              coinDetailed.decimals,
-              coinDetailed.name ?? '',
-              coinDetailed.symbol ?? '',
-          )
+        ? createERC20Token(chainId, coin.eth_address ?? ETH_ADDRESS, decimals ?? 0, coin.name ?? '', coin.symbol ?? '')
```
Comment (guanbinrui) [inline packages/maskbook/src/plugins/Trader/UI/trending/SearchResultView.tsx:161]: The portion after `??` is unnecessary.

```suggestion
        ? createERC20Token(chainId, coin.eth_address, decimals ?? 0, coin.name ?? '', coin.symbol ?? '')
```

File: packages/maskbook/src/plugins/Trader/UI/trending/SearchResultView.tsx [hunk 3]
```diff
@@ -154,14 +156,9 @@ export function SearchResultView(props: SearchResultViewProps) {
     const canSwap = trending.coin.eth_address || trending.coin.symbol.toLowerCase() === 'eth'
     const swapTabIndex = dataProvider !== DataProvider.UNISWAP ? 3 : 1
     const fromToken = chainId === ChainId.Mainnet && coin.is_mirrored ? UST : createEtherToken(chainId)
+    const { decimals } = coinDetailed ?? trending.coin
```
Comment (guanbinrui) [inline packages/maskbook/src/plugins/Trader/UI/trending/SearchResultView.tsx:159]: Maybe reduce this local variable.

File: packages/maskbook/src/plugins/Trader/UI/trending/SearchResultView.tsx (hunk 2 above)
Comment (zhouhanseng) [reply packages/maskbook/src/plugins/Trader/UI/trending/SearchResultView.tsx:161]: ok

File: packages/maskbook/src/plugins/Trader/UI/trending/SearchResultView.tsx (hunk 3 above)
Comment (zhouhanseng) [reply packages/maskbook/src/plugins/Trader/UI/trending/SearchResultView.tsx:159]: Does `createERC20Token()` compute the decimals out?

```
export function createERC20Token(chainId: ChainId, address: string, decimals: number, name: string, symbol: string) {
    return {
        type: EthereumTokenType.ERC20,
        chainId,
        address,
        decimals,
        name,
        symbol,
    } as ERC20TokenDetailed
}
```

File: packages/maskbook/src/plugins/Trader/UI/trending/SearchResultView.tsx (hunk 2 above)
Comment (guanbinrui) [reply packages/maskbook/src/plugins/Trader/UI/trending/SearchResultView.tsx:161]: Cause it's leading by `trending.coin.eth_address`. That is the same as `coin.eth.address`.

Comment (zhouhanseng) [reply packages/maskbook/src/plugins/Trader/UI/trending/SearchResultView.tsx:161]: ok

**Review by guanbinrui — APPROVED** [review]
