### PR TITLE
fix: clicking connect-wallet button should open wallet select dialog

### LINKED ISSUE #3602: [Bug] Wrong page displays by clicking "Connect Wallet" on the left menu bar.
### How to reproduce?

1.Don't connect any wallet in Twitter;
2.Click "Connect Wallet" on the left menu bar;
3.Check what will display.

### What happened?
Create/import Mask wallet page displays.
截屏2021-07-07 下午3 25 43

### What should happen?
Connect Wallet page should be display.
截屏2021-07-07 下午3 25 55

### Mask Version:

- [x] (Browser) Installed from the extension store (version:1.34 )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

### PR DESCRIPTION
**Pull request by UncleBill**
closes #3602

### CODE REVIEW

File: packages/maskbook/src/plugins/Wallet/SNSAdaptor/SelectProviderDialog/index.tsx [hunk 1]
```diff
@@ -183,7 +188,10 @@ function SelectProviderDialogUI(props: SelectProviderDialogUIProps) {
                     // create a new wallet
                     if (isEnvironment(Environment.ManifestOptions))
                         history.push(`${DashboardRoute.Wallets}?create=${Date.now()}`)
-                    else await Services.Welcome.openOptionsPage(DashboardRoute.Wallets, `create=${Date.now()}`)
+                    else {
+                        // await Services.Welcome.openOptionsPage(DashboardRoute.Wallets, `create=${Date.now()}`)
```
Comment (guanbinrui) [inline packages/maskbook/src/plugins/Wallet/SNSAdaptor/SelectProviderDialog/index.tsx:192]:
```suggestion
```

Comment (UncleBill) [reply packages/maskbook/src/plugins/Wallet/SNSAdaptor/SelectProviderDialog/index.tsx]: fixed in https://github.com/DimensionDev/Maskbook/pull/3631/commits/9d3a0d4cec11f4da01c80875a38011ae4ef0afcc

**Comment by wenluomask** [comment]
Checked in  fix/connect-wallet branch

**Review by guanbinrui — APPROVED** [review]
