### PR TITLE
fix: set mask as the primary token

### LINKED ISSUE #2925: [Demand] Set Mask as the primary token
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

Set Mask as the first token in the `<SelectTokenDialog />` component.

## Part 2: Problem to Solve

Sort tokens here [FixedTokenList.tsx#L66](https://github.com/DimensionDev/Maskbook/blob/4808386006f389db0cde161676c21f73a075bb20/packages/maskbook/src/extension/options-page/DashboardComponents/FixedTokenList.tsx#L66).

### PR DESCRIPTION
**Pull request by lelenei**
closes #2925

### CODE REVIEW

**Review by Jack-Works — DISMISSED** [review]

File: packages/maskbook/src/extension/options-page/DashboardComponents/FixedTokenList.tsx [hunk 1]
```diff
@@ -63,12 +67,15 @@ export function FixedTokenList(props: FixedTokenListProps) {
     if (state === TokenListsState.LOADING_SEARCHED_TOKEN) return renderPlaceholder('Loading token...')
     if (!erc20TokensDetailed.length) return renderPlaceholder('No token found')
 
+    const MaskTokens = erc20TokensDetailed.filter((x) => isSameAddress(MASK_ADDRESS, x.address))
     const filteredTokens = erc20TokensDetailed.filter(
         (x) =>
             (!includeTokens.length || includeTokens.some((y) => isSameAddress(y, x.address))) &&
-            (!excludeTokens.length || !excludeTokens.some((y) => isSameAddress(y, x.address))),
+            (!excludeTokens.length || !excludeTokens.some((y) => isSameAddress(y, x.address))) &&
+            !isSameAddress(MASK_ADDRESS, x.address),
```
Comment (guanbinrui) [inline packages/maskbook/src/extension/options-page/DashboardComponents/FixedTokenList.tsx:75]: Please revert this.

**Comment by lelenei** [comment]
image

**Review by guanbinrui — APPROVED** [review]

**Review by septs — APPROVED** [review]
