### PR TITLE
Red packet history service

### LINKED ISSUE #1581: [Demand] Added red packet history
## Catalogue

- [ ] UI/UX
- [ ] Maskbook Core Feature
- [x] Maskbook Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
    - /* List it here */

## Part 1: Introduction and Background
Our existing red packet history is kind of broken. If a transaction receipt is not received locally, it won't show up in our red packet history even though it is confirmed on the network.

## Part 2: Problem to Solve
Add a new way to query the history of the given address and the red packet contract to get both created and claimed red packets history.

## Part 3: Expected Behavior
- [x] Find the best option to query the contract (Etherscan, web3.js, etc)
- [x] Query the contract to get the red packet creation history of the given address
- [x] Query the contract to get the red packet claim history of the given address
- [ ] Upgrade the contract to make this query easier by providing an API

### PR DESCRIPTION
**Pull request by septs**
closes #1581

### CODE REVIEW

File: src/extension/options-page/DashboardDialogs/Wallet.tsx [hunk 1]
```diff
@@ -629,7 +629,20 @@ export function DashboardWalletHistoryDialog(
 
     const [redPacketRecords, setRedPacketRecords] = useState<RedPacketRecord[]>([])
     const inboundRecords = redPacketRecords.filter((record) => record.claim_address === wallet.address)
-    const outboundRecords = redPacketRecords.filter((record) => record.sender_address === wallet.address)
+    // const outboundRecords = redPacketRecords.filter((record) => record.sender_address === wallet.address)
+
+    // region HACK: THIS TEMPORARY CODE
```
Comment (Jack-Works) [inline src/extension/options-page/DashboardDialogs/Wallet.tsx:634]: Why do you say so?

Comment (septs) [reply src/extension/options-page/DashboardDialogs/Wallet.tsx:634]: i need redesign data structure,
match maskbook current wallet type system.

**Review by guanbinrui — APPROVED** [review]

**Review by Jack-Works — APPROVED** [review]
