### PR TITLE
fix: account is absent

### LINKED ISSUE #3863: [Crash] Error: invalid address
I was checking the tweet with pooltogether link, I change to account tab, then Mask report an error.
Here is the tweet I checked: https://twitter.com/WEN6666661/status/1423146613363539980
> invalid address (argument="address", value="", code=INVALID_ARGUMENT, version=address/5.4.0) (argument="account", value="", code=INVALID_ARGUMENT, version=abi/5.0.7)

Error stack:

<pre>Error: invalid address (argument="address", value="", code=INVALID_ARGUMENT, version=address/5.4.0) (argument="account", value="", code=INVALID_ARGUMENT, version=abi/5.0.7)
    at Logger.makeError (chrome-extension://fmfgjaeiddkdhgmioobeancabcmkpfab/js/1528.js:3445:23)
    at Logger.throwError (chrome-extension://fmfgjaeiddkdhgmioobeancabcmkpfab/js/1528.js:3454:20)
    at Logger.throwArgumentError (chrome-extension://fmfgjaeiddkdhgmioobeancabcmkpfab/js/1528.js:3457:21)
    at AddressCoder._throwError (chrome-extension://fmfgjaeiddkdhgmioobeancabcmkpfab/js/npm-ns.ethersproject.abi.js:851:31)
    at AddressCoder.encode (chrome-extension://fmfgjaeiddkdhgmioobeancabcmkpfab/js/npm-ns.ethersproject.abi.js:977:18)
    at chrome-extension://fmfgjaeiddkdhgmioobeancabcmkpfab/js/npm-ns.ethersproject.abi.js:1060:19
    at Array.forEach (<anonymous>)
    at pack (chrome-extension://fmfgjaeiddkdhgmioobeancabcmkpfab/js/npm-ns.ethersproject.abi.js:1046:12)
    at TupleCoder.encode (chrome-extension://fmfgjaeiddkdhgmioobeancabcmkpfab/js/npm-ns.ethersproject.abi.js:1354:16)
    at AbiCoder.encode (chrome-extension://fmfgjaeiddkdhgmioobeancabcmkpfab/js/npm-ns.ethersproject.abi.js:1443:15)</pre>

## Build info
- Version: 1.35.0
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-08-05T08:14:00.707Z
- VERSION: v1.29.12-718-g00a1b682c

## Git (*):

00a1b682c (develop) on tag "v1.35.0"
git@github.com:DimensionDev/Maskbook.git

### PR DESCRIPTION
**Pull request by guanbinrui**
closes #3863

### CODE REVIEW

File: packages/maskbook/src/plugins/PoolTogether/hooks/useAccountBalances.ts [hunk 1]
```diff
@@ -18,7 +20,7 @@ export function useAccountBalance(pools: Pool[]) {
     const [results, calls, _, callback] = useMutlipleContractSingleData(
         ticketContracts,
         new Array(ticketContracts.length).fill('balanceOf'),
-        [account],
+        [account || ZERO_ADDRESS],
```
Comment (septs) [inline packages/maskbook/src/plugins/PoolTogether/hooks/useAccountBalances.ts:23]:
```suggestion
        [account ?? ZERO_ADDRESS],
```

Comment (guanbinrui) [reply packages/maskbook/src/plugins/PoolTogether/hooks/useAccountBalances.ts:23]: It could be an empty string.

**Review by UncleBill — APPROVED** [review]
