### PR TITLE
fix: the list boxes in Poll can not be expanded fully

### LINKED ISSUE #3366: [Bug] The list boxes in Poll can not be expanded fully
### How to reproduce?

1.On Twitter, click mask icon and then Poll(Beta);
2.In pop window, choose number greater than 14 in the list box of hours;
3.Choose number greater than 40 in the list box of minutes.

### What happened?
User can not choose number greater than 14 in the list box of hours and greater than 40 in the list box of minutes.

### What should happen?
The list boxes of hours and minutes can be expanded fully.

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [x] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

### PR DESCRIPTION
**Pull request by lelenei**
closes #3366

### CODE REVIEW

**Review by guanbinrui — DISMISSED** [review]

File: packages/maskbook/src/plugins/Polls/SNSAdaptor/PollsDialog.tsx [hunk 1]
```diff
@@ -120,7 +123,10 @@ function NewPollUI(props: PollsDialogProps & NewPollProps) {
         return usePortalShadowRoot((container) => (
             <Select
                 variant="standard"
-                MenuProps={{ container }}
+                MenuProps={{
+                    container: container,
```
Comment (septs) [inline packages/maskbook/src/plugins/Polls/SNSAdaptor/PollsDialog.tsx:127]:
```suggestion
                    container,
```

**Review by septs — APPROVED** [review]

**Review by guanbinrui — APPROVED** [review]
