### PR TITLE
fix: bugfix for tips crash

### LINKED ISSUE #7677: [Crash] TypeError: bindings.find is not a function
I recovered backup  and then went to application board, then Mask reports an error.

> bindings.find is not a function

Error stack:

<pre>useTipsWalletsList/result<@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/js/chunk.114.js:820:43
useTipsWalletsList@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/js/chunk.114.js:817:31
TipsEntranceDialog@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/js/chunk.114.js:2020:36
Xh@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/js/npm.react-dom.js:376:137
dj@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/js/npm.react-dom.js:406:258
Wk@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/js/npm.react-dom.js:501:88
Vk@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/js/npm.react-dom.js:489:391
Uk@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/js/npm.react-dom.js:489:322
Jk@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/js/npm.react-dom.js:489:180
Ok@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/js/npm.react-dom.js:480:88
Hk@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/js/npm.react-dom.js:477:429
J@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/js/284.js:3069:204
R@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/js/284.js:3070:128
@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/polyfill/ecmascript.js:3283:12
run@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/polyfill/ecmascript.js:3257:5
listener@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/polyfill/ecmascript.js:3268:6
EventHandlerNonNull*@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/polyfill/ecmascript.js:3306:5
__webpack_require__@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/polyfill/ecmascript.js:48:30
@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/polyfill/ecmascript.js:3210:41
__webpack_require__@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/polyfill/ecmascript.js:48:30
@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/polyfill/ecmascript.js:3200:20
__webpack_require__@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/polyfill/ecmascript.js:48:30
@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/polyfill/ecmascript.js:137:20
__webpack_require__@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/polyfill/ecmascript.js:48:30
@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/polyfill/ecmascript.js:112:18
@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/polyfill/ecmascript.js:115:10
@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/polyfill/ecmascript.js:4146:15
@moz-extension://3d3a847c-efb0-4b78-826e-dc3c7db7ac25/polyfill/ecmascript.js:4147:4
</pre>

## Build info
- Version: 2.11.3
- NODE_ENV: production
- target: firefox
- build: stable
- architecture: web
- BUILD_DATE: 2022-10-13T04:37:05.208Z
- VERSION: v1.29.12-2858-g459860840

## Git (*):

459860840 (hotfix/2.11.3)
https://github.com/DimensionDev/Maskbook

### PR DESCRIPTION
**Pull request by nuanyang233**
fix: bugfix for crash

## Description

Closes #7677 MF-2424
## Type of change

- [ ] Documentation
- [ ] Code refactoring (Restructuring existing code w/o changing its observable behavior)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (a fix or feature that would make something no longer possible to do/require old user must upgrade their Mask Network to this new version)

## Checklist

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
  - [ ] I have removed all in development `console.log`s
  - [ ] I have removed all commented code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have read [Internationalization Guide](https://github.com/DimensionDev/Maskbook/blob/develop/docs/i18n-guide.md) and moved text fields to the i18n JSON file.

If this PR depends on external APIs:

- [ ] I have configured those APIs with CORS headers to let extension requests get passed. 
  - chrome extension: `chrome-extension://[id]`
  - firefox extension: `moz-extension://[id]`
- [ ] I have delegated all web requests to the background service via the internal RPC bridge.

### CODE REVIEW

File: packages/mask/src/plugins/Tips/hooks/useTipsWalletsList.ts [hunk 1]
```diff
@@ -20,10 +20,13 @@ export function useTipsWalletsList(
...
             x.isPublic = 1
-            const matched = bindings?.find((proof) => isSameAddress(x.identity, proof.identity))
+            const matched = bindings as any as {
+                defaultAddress: string
+                hiddenAddresses: string[]
+            }
             if (matched) {
-                x.isDefault = matched.isDefault
-                x.isPublic = matched.isPublic
+                x.isDefault = matched.defaultAddress === x.identity ? 1 : 0
```
Comment (guanbinrui) [inline packages/mask/src/plugins/Tips/hooks/useTipsWalletsList.ts]: isSameAddress？

**Review by guanbinrui — APPROVED** [review]
