### PR TITLE
fix: guarantee persona proofs

### LINKED ISSUE #11920: [Crash] TypeError: proofs.filter is not a function
I was *doing something...*, then Mask reports an error.

> proofs.filter is not a function

Error stack:

<pre>TypeError: proofs.filter is not a function
  at /entry/popups.js:49:19747
  at Object.useMemo (/entry/popups.js:1164:115991)
  at exports1.useMemo (/entry/popups.js:1221:12857)
  at usePersonaContext (/entry/popups.js:49:19484)
  at Provider (/entry/popups.js:44:12635)
  at renderWithHooks (/entry/popups.js:1164:87355)
  at updateFunctionComponent (/entry/popups.js:1164:134189)
  at beginWork (/entry/popups.js:1164:159732)
  at performUnitOfWork (/entry/popups.js:1164:259597)
  at workLoopSync (/entry/popups.js:1164:256982)</pre>

## Build info
- Version: 2.27.1
- NODE_ENV: production
- userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
- build: stable
- BUILD_DATE: 2024-11-04T03:15:59.666Z

## Git (*):
450c3076118d17f795e9c9af3432afbbd768ed9c (HEAD)

### PR DESCRIPTION
**Pull request by swkatmask**
closes #11920 

mf-0000

### CODE REVIEW

File: packages/shared/src/hooks/usePersonaProofs.ts [hunk 1]
```diff
@@ -10,7 +10,7 @@ export function usePersonaProofs(publicKey?: string): UseQueryResult<BindingProo
         queryFn: async () => {
             if (Sniffings.is_popup_page) await NextIDProof.clearPersonaQueryCache(publicKey!)
             const binding = await NextIDProof.queryExistedBindingByPersona(publicKey!)
-            return binding?.proofs ?? EMPTY_LIST
+            return Array.isArray(binding?.proofs) ? binding.proofs : EMPTY_LIST
```
Comment (Jack-Works) [inline packages/shared/src/hooks/usePersonaProofs.ts:13]: what else can `binding?.proofs` be other than `undefined` or `null`?

Comment (swkatmask) [reply packages/shared/src/hooks/usePersonaProofs.ts:13]: Do not know, can't reproduce. https://github.com/DimensionDev/Maskbook/issues/11920

**Review by guanbinrui — APPROVED** [review]
