### PR TITLE
fix: popup bugfix

### LINKED ISSUE #4943: [Bug] Change network in popup will flash to create/import page and it took a long time.
### How to reproduce?

1. Change network in popup;

### What happened?
It will flash to create/import page and it took a long time.
https://user-images.githubusercontent.com/85149605/143604148-818f7533-609d-493d-9317-35acab847faa.mov

### What should happen?
It should not take so long time to change network.

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

### LINKED ISSUE #4944: [Bug]Mask Wallet still showed connected status in Twitter after deletion
### How to reproduce?

1.Connect a mask wallet in Twitter;
2.Delete the wallet;
3.Check whether wallet showed connected in Twitter.

### What happened?
Mask Wallet still showed connected status in Twitter after deletion. I tried to refresh page but it doesn't work.
Screen Shot 2021-11-26 at 11 48 34 PM

### What should happen?
It should show connect wallet button after no wallet connected.

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

### PR DESCRIPTION
**Pull request by nuanyang233**
close #4943 
close #4944 
hidden testnet in production env

### CODE REVIEW

File: packages/mask/src/extension/popups/components/NetworkSelector/index.tsx [hunk 1]
```diff
@@ -79,9 +84,11 @@ export interface NetworkSelectorUIProps {
 export const NetworkSelectorUI = memo<NetworkSelectorUIProps>(({ currentNetwork, onChainChange }) => {
     const { classes } = useStyles()
     const networks = getRegisteredWeb3Networks()
+
     const [menu, openMenu] = useMenu(
         ...(networks
             ?.filter((x) => x.networkSupporterPluginID === NetworkPluginID.PLUGIN_EVM)
+            .filter((x) => (Flags.support_eth_network_switch ? true : x.isMainnet))
```
Comment (guanbinrui) [inline packages/mask/src/extension/popups/components/NetworkSelector/index.tsx:91]:
```suggestion
            .filter((x) => (Flags.support_testnets ? true : x.isMainnet))
```

**Review by guanbinrui — APPROVED** [review]
