### PR TITLE
Filter groups by current selected identity

### LINKED ISSUE #494: [Bug] Private groups and friends shared between different persona
# Bug Report

### System

- OS: macos mojave 
- OS Version: 10.14.6

### Browser

- Browser: Chrome
- Browser Version: 78.0.3904.108 (Official Build) (64-bit)

### Maskbook

- Maskbook Version: 1.8.7
- Installation: Self-Complied
- Build Commit: c6a90099fc6343ab96f59c39e327b55a1216f87b
### Actual Behavior

Private groups and friends data shared between different persona in same machine.

image

### How To Reproduce

+ add two different persona and finish the setup steps;
+ add some friends in each persona;

### PR DESCRIPTION
**Pull request by guanbinrui**
This PR includes:

+ Add `useCurrentGroupsList()`

Close #494.

### CODE REVIEW

File: src/components/DataSource/useActivatedUI.ts [hunk 1]
```diff
@@ -20,3 +20,9 @@ export function useCurrentIdentity(noDefault?: boolean): Profile | null {
     const current = useValueRef(currentSelectedIdentity[getActivatedUI().networkIdentifier])
     return all.find(i => i.identifier.toText() === current) || (noDefault ? null : all[0])
 }
+export function useCurrentGroupsList() {
+    const groups = useGroupsList()
+    const currentIdentity = useCurrentIdentity()
+    if (!currentIdentity) return []
+    return groups.filter(x => x.identifier.ownerIdentifier.equals(currentIdentity.identifier))
```
Comment (Jack-Works) [inline src/components/DataSource/useActivatedUI.ts]: Note, invoke getter on `ownerIdentifier` may throw. You should check the `isVirtual` property before using it. (It maybe a type design failure maybe we should change the type `ownerIdentifier` to `null | ProfileIdentifier` instead of throw)
