### PR TITLE
fix: some invalid url wrongly detected by anchorme

### LINKED ISSUE #3185: [Bug] [Collectible] Fails to parse url created by aaa the URL Lengthener.
## Bug Info

Url created by https://aaa.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.com/ can't be parsed correctly

### How to reproduce?

1. Visit https://twitter.com/TejasKumar_/status/1393593636848287744
2.
3.

### What happened?

image

### Mask Version:

- [x] (Browser) Installed from the extension store (Version 1.32.1)
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

### PR DESCRIPTION
**Pull request by UncleBill**
url like `https://…a.com`. see alexcorvi/anchorme.js/issues/109

closes #3185

### CODE REVIEW

File: packages/shared/src/utils/parseURL.ts [hunk 1]
```diff
@@ -1,4 +1,14 @@
...
+        .list(text)
+        .map((x) => x.string)
+        .filter((y) => {
+            try {
+                new URL(y)
+                return true
+            } catch {
+                return false
+            }
+        })
```
Comment (septs) [inline packages/shared/src/utils/parseURL.ts:13]: plz extract as function, `.filter(isValidURL)`

Comment (Jack-Works) [reply packages/shared/src/utils/parseURL.ts:13]: I think we're ok with this as a temporary fix

File: packages/shared/src/utils/parseURL.ts [hunk 2]
```diff
@@ -1,4 +1,14 @@
 import parser from 'anchorme'
-export function parseURL(string: string) {
-    return parser.list(string).map((x) => x.string)
+export function parseURL(text: string) {
+    return parser
+        .list(text)
+        .map((x) => x.string)
+        .filter((y) => {
+            try {
```
Comment (Jack-Works) [inline packages/shared/src/utils/parseURL.ts:7]:
```suggestion
            // See https://github.com/alexcorvi/anchorme.js/issues/109
            try {
```

**Review by Jack-Works — APPROVED** [review]

**Review by guanbinrui — APPROVED** [review]
