### PR TITLE
fix: user can create persona by more than 24 characters

### LINKED ISSUE #3362: [Bug] User can create persona by more than 24 characters
### How to reproduce?

1. Enter create persona page from welcome page;
2. Create persona by a name more than 24 characters;
3. In dashboard, enter personas page to create new persona by a name more than 24 characters.

### What happened?
In create persona page , user is able to create persona by a name more than 24 characters.
In create new persona pop window, user is able to create persona by a name less than 31 characters.
### What should happen?
user is unable to create persona by a name more than 24 characters and display message "Maximum length is 24 characters long".

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [x] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

### PR DESCRIPTION
**Pull request by lelenei**
closes #3362

### CODE REVIEW

**Comment by septs** [comment]
@lelenei plz rename pr title.

**Review by guanbinrui — APPROVED** [review]

File: packages/maskbook/src/extension/options-page/DashboardRouters/Setup.tsx [hunk 1]
```diff
@@ -259,7 +259,9 @@ export function CreatePersona() {
                         onKeyDown={(e) => {
                             if (e.key === 'Enter') {
                                 e.preventDefault()
-                                createPersonaAndNext()
+                                if (name.length !== 0 && !checkInputLengthExceed(name)) {
```
Comment (septs) [inline packages/maskbook/src/extension/options-page/DashboardRouters/Setup.tsx:262]:
```suggestion
                                if (!checkInputLengthExceed(name) && name.length > 0) {
```

File: packages/maskbook/src/extension/options-page/DashboardDialogs/Persona/Create.tsx [hunk 2]
```diff
@@ -49,7 +49,9 @@ export function DashboardPersonaCreateDialog(props: WrappedDialogProps) {
                                 onKeyDown={(e) => {
                                     if (e.key === 'Enter') {
                                         e.preventDefault()
-                                        createPersonaAndNext()
+                                        if (!checkInputLengthExceed(name) && name.length !== 0) {
```
Comment (septs) [inline packages/maskbook/src/extension/options-page/DashboardDialogs/Persona/Create.tsx:52]:
```suggestion
                                        if (!checkInputLengthExceed(name) && name.length > 0) {
```

**Review by septs — APPROVED** [review]

**Review by guanbinrui — APPROVED** [review]
