### PR TITLE
fix: user can create persona by more than 24 characters

### LINKED ISSUE #3362: [Bug] User can create persona by more than 24 characters
### How to reproduce?

1. Enter create persona page from welcome page;
2. Create persona by a name more than 24 characters;
3. In dashboard, enter personas page to create new persona by a name more than 24 characters.

### What happened?
In create persona page , user is able to create persona by a name more than 24 characters.
In create new persona pop window, user is able to create persona by a name less than 31 characters.
### What should happen?
user is unable to create persona by a name more than 24 characters and display message "Maximum length is 24 characters long".

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [x] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

### PR DESCRIPTION
**Pull request by lelenei**
closes #3362

### CODE REVIEW

**Review by Jack-Works — APPROVED** [review]

File: packages/maskbook/src/extension/options-page/DashboardDialogs/Persona/Create.tsx [hunk 1]
```diff
@@ -45,7 +52,7 @@ export function DashboardPersonaCreateDialog(props: WrappedDialogProps) {
                                 required
                                 label={t('name')}
                                 value={name}
-                                onChange={(e) => setName(e.target.value)}
+                                onChange={onChange}
```
Comment (UncleBill) [inline packages/maskbook/src/extension/options-page/DashboardDialogs/Persona/Create.tsx:55]: suggestion:

Add a [`maxlength`][1] to the `input` element

[1]: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/maxlength

**Review by UncleBill — APPROVED** [review]

**Review by Jack-Works — DISMISSED** [review]

**Review by guanbinrui — DISMISSED** [review]

**Comment by guanbinrui** [comment]
@lelenei Please rebase this branch onto hotfix/1.33.2

**Review by Jack-Works — APPROVED** [review]

**Review by guanbinrui — APPROVED** [review]

**Comment by wenluomask** [comment]
Checked in Hotfix-1.33.2
