### PR TITLE
fix: capture replaced transactions by querying explorer API

### LINKED ISSUE #4543: [Bug] Need to check unconfirmed transaction status
### How to reproduce?

1. Close dialog during unlock token or NFT.
2. Open the dialog again before the transaction was confirmed.

### What happened?
We can do unlock operation again since the on-chain transaction was not checked.

### What should happen?
This is a common issue, we need to check the on-chain transaction status besides getting the unlock(approve) state. 

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

### PR DESCRIPTION
**Pull request by guanbinrui**
Suppose the user uses an external wallet provider to replace a transaction. We can reach the new transaction hash by querying the explorer API. For those MaskWallet maintains transactions, we can figure them by comparing two nonces. However, accounts from external wallets cannot do this cause we don't track the nonce for those accounts.

closes #4543

### CODE REVIEW

**Comment by guanbinrui** [comment]
@DimensionDev/qa

**Comment by wenluomask** [comment]
1. If spped up the tx for sending ITO, tx replaced but ITO's status is still "waiting for confirmation", it is supposed to confirm and go to Compose;
Screen Shot 2021-12-13 at 5 21 05 PM

Same situation for withdrawal of ITO and creation of lucky drop etc.
Screen Shot 2021-12-13 at 5 33 30 PM

2. Tx cancelled will still keep the claim button of lucky drop to be "claiming" status; It can be fixed if I refresh page;
Screen Shot 2021-12-13 at 5 45 10 PM

File: packages/mask/src/plugins/Wallet/services/transaction/database.ts [hunk 1]
```diff
@@ -61,15 +61,16 @@ export async function replaceRecentTransaction(
...
     newHash: string,
-    payload?: JsonRpcPayload,
+    newPayload?: JsonRpcPayload,
 ) {
     const now = new Date()
     const recordId = getRecordId(chainId, address)
     const chunk = await PluginDB.get('recent-transactions', recordId)
     const transaction = chunk?.transactions.find((x) => x.hash === oldHash)
     if (!transaction) throw new Error('Failed to find the old transaction.')
+    if (transaction.hash === newHash) return
```
Comment (zhouhanseng) [inline packages/mask/src/plugins/Wallet/services/transaction/database.ts:71]: `isSameAddress(transaction.hash, newHash)`

File: packages/web3-providers/src/explorer/index.ts [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+        offset?: number
+        apikey?: string
+    }> = {},
+) {
+    const response = await fetch(
+        urlcat(url, {
+            module: 'account',
+            action: 'txlist',
+            address: account.toLowerCase(),
+            startBlock: 0,
```
Comment (zhouhanseng) [inline packages/web3-providers/src/explorer/index.ts:21]: Better to use a larger number, e.g. the block number of tx in watched transactions or the original tx or something.

File: packages/web3-providers/src/explorer/index.ts [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+            endblock: 999999999999,
```
Comment (zhouhanseng) [inline packages/web3-providers/src/explorer/index.ts:22]: `await web3.eth.getBlockNumber()` use the latest block number

File: packages/mask/src/plugins/Wallet/services/transaction/watcher.ts [hunk 4]
```diff
@@ -51,51 +107,132 @@ async function getTransactionReceipt(chainId: ChainId, hash: string) {
...
+    const latestTransactions = await getLatestTransactions(account, API_URL, {
+        offset: CHECK_LATEST_SIZE,
+        apikey: first(API_KEYS),
+    })
+
+    for (const latestTransaction of latestTransactions) {
+        const [watchedHash, watchedTransaction] =
+            watchedTransactions.find(([hash, transaction]) => {
+                // the transaction hash exact matched
+                if (latestTransaction.hash === hash) return true
```
Comment (zhouhanseng) [inline packages/mask/src/plugins/Wallet/services/transaction/watcher.ts:137]: If hashes are the same, why we need to call `replaceRecentTransaction()`? Since speed up create a new tx.

File: packages/mask/src/plugins/Wallet/services/transaction/database.ts (hunk 1 above)
Comment (guanbinrui) [reply packages/mask/src/plugins/Wallet/services/transaction/database.ts:71]: Not necessary for hash.

File: packages/mask/src/plugins/Wallet/services/transaction/watcher.ts (hunk 4 above)
Comment (guanbinrui) [reply packages/mask/src/plugins/Wallet/services/transaction/watcher.ts:137]: The latest transaction fetched from explorer may not be a replaced one.

File: packages/web3-providers/src/explorer/index.ts (hunk 3 above)
Comment (guanbinrui) [reply packages/web3-providers/src/explorer/index.ts:22]: Not necessary. The explorer API will handle this.

File: packages/web3-providers/src/explorer/index.ts (hunk 2 above)
Comment (guanbinrui) [reply packages/web3-providers/src/explorer/index.ts:21]: The primary purpose of this API is to fetch the latest n transactions. The explorer API will handle this even with these extremely bad parameters.

File: packages/mask/src/plugins/Wallet/services/transaction/watcher.ts [hunk 5]
```diff
@@ -150,7 +150,7 @@ async function checkAccount(chainId: ChainId, account: string) {
                 )
             }) ?? []
 
-        if (!watchedHash || !watchedTransaction?.payload) continue
+        if (!watchedHash || !watchedTransaction?.payload || watchedHash !== latestTransaction.hash) continue
```
Comment (zhouhanseng) [inline packages/mask/src/plugins/Wallet/services/transaction/watcher.ts:153]:
```suggestion
        if (!watchedHash || !watchedTransaction?.payload || watchedHash === latestTransaction.hash) continue
```

**Comment by wenluomask** [comment]
4. Use mask wallet to swap, confirmation for swap will keep loading;
Screen Shot 2021-12-20 at 5 40 06 PM

5. I tried to donate in gitcoin, first speed up, and then donate the same amount and gas price for second time. 2 pending showed, but activity became empty.
Screen Shot 2021-12-20 at 5 52 36 PM

6. I see the message: Failed to find transaction tx, in this case, should ignore the pending case, so it won't keep pending.
