### PR TITLE
fix: add dHEDGE icon

### LINKED ISSUE #3365: [Bug] dHEDGE miss icon in plugin page
### How to reproduce?

Screen Shot 2021-06-15 at 13 32 14

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

### PR DESCRIPTION
**Pull request by septs**
closes #3365

### CODE REVIEW

File: packages/maskbook/src/plugins/dHEDGE/UI/Icon.tsx [hunk 1]
```diff
@@ -0,0 +1,13 @@
+import { SvgIcon, SvgIconProps } from '@material-ui/core'
+import type { FC } from 'react'
+
+export const PluginIcon: FC<SvgIconProps> = (props) => (
+    <SvgIcon {...props}>
+        <svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
```
Comment (zhouhanseng) [inline packages/maskbook/src/plugins/dHEDGE/UI/Icon.tsx:6]: Extract the svg to a single file, then import it into React component

**Review by Jack-Works — APPROVED** [review]

**Review by zhouhanseng — APPROVED** [review]
