### PR TITLE
fix: treat inline svg code as locale resource

### LINKED ISSUE #7270: /^data|blob:|\w+-extension:\/\//.test(url)
```suggestion
    return /^data|blob:|\w+-extension:\/\//.test(url)
```

_Originally posted by @guanbinrui in https://github.com/DimensionDev/Maskbook/pull/7240#discussion_r958473106_

### PR DESCRIPTION
**Pull request by UncleBill**
closes #7270

### CODE REVIEW

**Review by guanbinrui — APPROVED** [review]

**Comment by UncleBill** [comment]
image

File: packages/web3-shared/base/src/utils/resolver.ts [hunk 1]
```diff
@@ -234,8 +234,7 @@ export const isIpfsCid = (cid: string) => {
 }
 
 export const isLocaleResource = (url: string): boolean => {
-    // base64 image
-    return /^data|blob:|(chrome|moz)-extension:\/\//.test(url)
+    return /^data|blob:|(chrome|moz)-extension:\/\/|<svg\s/.test(url)
```
Comment (Jack-Works) [inline packages/web3-shared/base/src/utils/resolver.ts:237]: still not resolved. should be able to support `*-extension` protocol.
