### PR TITLE
fix: ito ui detail

### LINKED ISSUE #2996: [Demand] Rename Qualification Contract to Plugin Contract
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature (ITO)
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

Rename `Qualification Contract` to `Plugin Contract` in the realm of the ITO plugin.

### LINKED ISSUE #2997: [Demand] Hide the default qualification contract address
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature (ITO)
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background

If the plugin contract field is not filled. The default qualification contract address will be listed in the confirmation dialog which will mislead the user. So we'd better not to list it in that dialog. Otherwise, if the user has assigned a custom value, it will be listed.

### PR DESCRIPTION
**Pull request by zhouhanseng**
closes #2996 
closes #2997

### CODE REVIEW

**Review by guanbinrui — APPROVED** [review]

File: packages/maskbook/src/plugins/ITO/UI/ConfirmDialog.tsx [hunk 1]
```diff
@@ -208,7 +211,9 @@ export function ConfirmDialog(props: ConfirmDialogProps) {
                         <Typography>{dateTimeFormat(poolSettings?.endTime!)}</Typography>
                     </Paper>
                 </Grid>
-                {poolSettings?.qualificationAddress && poolSettings?.advanceSettingData.contract ? (
+                {poolSettings?.advanceSettingData.contract &&
```
Comment (septs) [inline packages/maskbook/src/plugins/ITO/UI/ConfirmDialog.tsx:214]: extract to named variable?

File: packages/maskbook/src/plugins/ITO/UI/ConfirmDialog.tsx [hunk 2]
```diff
@@ -208,7 +211,9 @@ export function ConfirmDialog(props: ConfirmDialogProps) {
...
+                poolSettings?.qualificationAddress &&
+                poolSettings?.qualificationAddress !== DEFAULT_QUALIFICATION_ADDRESS ? (
```
Comment (guanbinrui) [inline packages/maskbook/src/plugins/ITO/UI/ConfirmDialog.tsx:216]:
```suggestion
                poolSettings?.qualificationAddress !== DEFAULT_QUALIFICATION_ADDRESS ? (
```

**Review by guanbinrui — APPROVED** [review]

**Review by septs — APPROVED** [review]

**Review by guanbinrui — APPROVED** [review]
