### PR TITLE
Early open option page if no wallet was imported

### LINKED ISSUE #750: [Bug] Should not open option page when closing red packet dialog
# Bug Report

### Browser

- Browser: Chrome
- Browser Version: 78.0.3904.108 (Official Build) (64-bit)

### Maskbook

- Maskbook Version: 1.10.6
- Installation: Self-Complied
- Build Commit: 16ec636404e0ea92c67488ec09d2682e7f907204

### PR DESCRIPTION
**Pull request by guanbinrui**
This PR includes:

+ Fix #750 
+ Fix a UI bug

image

close #750

### CODE REVIEW

File: src/extension/options-page/Drawer.tsx [hunk 1]
```diff
@@ -62,9 +62,7 @@ const useStyles = makeStyles(theme => ({
     masktext: {
         display: 'block',
         marginTop: -20,
-        marginBottom: -20,
         width: 120,
-        height: 60,
```
Comment (SunriseFox) [inline src/extension/options-page/Drawer.tsx]: These should have been fixed in master branch.

Comment (guanbinrui) [reply src/extension/options-page/Drawer.tsx]: Revoked!

**Comment by SunriseFox** [comment]
If an effect is unexpectedly re-executed when closing the dialog, it may indicates that the component is re-created when it is meant to be destroyed... To be honest the design of `DialogRouter` may be very bad  as I don't quite know React much at that time...
