### PR TITLE
fix: hide the grant button if none persona was created

### LINKED ISSUE #3438: [Bug] Hide the grant button if none persona was created
### How to reproduce?

image

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

### PR DESCRIPTION
**Pull request by lelenei**
closes #3438

### CODE REVIEW

**Review by Jack-Works — APPROVED** [review]

File: packages/maskbook/src/extension/browser-action/UI.tsx [hunk 1]
```diff
@@ -132,20 +132,22 @@ function BrowserActionUI() {
...
-                            className={classes.button}
-                            variant="text"
-                            onClick={() => {
-                                if (Flags.no_web_extension_dynamic_permission_request) return
-                                requestSNSAdaptorPermission(ui).then(checkPermission)
+                    {ui.networkIdentifier === 'localhost' || identities.length === 0 ? null : (
+                        <Box
+                            sx={{
+                                display: 'flex',
                             }}>
```
Comment (septs) [inline packages/maskbook/src/extension/browser-action/UI.tsx:139]:
```suggestion
                            sx={{ display: 'flex' }}>
```

File: packages/maskbook/src/extension/browser-action/UI.tsx [hunk 2]
```diff
@@ -132,22 +130,21 @@ function BrowserActionUI() {
...
                     </Typography>
-                    {ui.networkIdentifier === 'localhost' || identities.length === 0 ? null : (
-                        <Box
-                            sx={{
-                                display: 'flex',
+
+                    <Box
+                        sx={{
+                            display: 'flex',
+                        }}>
```
Comment (septs) [inline packages/maskbook/src/extension/browser-action/UI.tsx]:
```suggestion
                    <Box sx={{ display: 'flex' }}>
```

File: packages/maskbook/src/extension/browser-action/UI.tsx (hunk 1 above)
Comment (UncleBill) [reply packages/maskbook/src/extension/browser-action/UI.tsx]: If our linters/formatters don't complain about it, we can just let it go.

Indeed, if these lines get joined, the code can be accepted by prettier, but prettier doesn't provide any option to join the lines.

I like the single-line object too. It's clear and clean. If only we can find a solution to handle this automatically. I come up with an idea: we can minify the code (without mangling variable names or removing comments), then format the code with prettier, and then we can get the object joined.

**Review by guanbinrui — APPROVED** [review]
