### PR TITLE
Hidden select/edit recipients link when post is shared to everyone

### LINKED ISSUE #745: [Bug] When a post is shared to everyone, user should not be able select/edit recipients later
# Bug Report

### System

- OS:
- OS Version:

### Browser

- Browser: chrome
- Browser Version:

### Maskbook

- Maskbook Version: store ver
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

## Bug Info
Screen Shot 2020-01-29 at 17 28 08

### Expected Behavior
When a post is shared to everyone, user should not be able select/edit recipients later; should have some place to indicate 'this is shared to everyone'
/* Write the expected behavior here. */

### Actual Behavior
For a post shared to everyone, user can still click and edit the recipients. see the pictures above.
/* Write the actual behavior here. */

### How To Reproduce
- post a tweet, shared with everyone;
- click and edit the recipients. 
/* Specify how it may be produced here. */

### PR DESCRIPTION
**Pull request by guanbinrui**
This PR includes:

- Hoist `postPayload` variable
- Add `sharedPublic` for `<DecryptPostSuccess />` and `<DecryptPostSuccessHeader />`
- Tweak style

close #745

### CODE REVIEW

**Comment by septs** [comment]
@SunriseFox Sorry

File: src/components/InjectedComponents/DecryptedPost.tsx [hunk 1]
```diff
@@ -161,6 +164,9 @@ export function DecryptPost(props: DecryptPostProps) {
         undefined,
     )
 
+    const postPayload = deconstructPayload(encryptedText, null)
```
Comment (guanbinrui) [inline src/components/InjectedComponents/DecryptedPost.tsx]: Here is the hoisted variable in order to evaluate it only once in single rendering task.

Comment (SunriseFox) [reply src/components/InjectedComponents/DecryptedPost.tsx]: According to my knowledge this seems the same as before... If you need to keep it between re-renders you need to wrap it with `useState`

Comment (guanbinrui) [reply src/components/InjectedComponents/DecryptedPost.tsx]: Updated to using `useState`

File: src/components/InjectedComponents/DecryptedPost.tsx [hunk 2]
```diff
@@ -161,6 +164,10 @@ export function DecryptPost(props: DecryptPostProps) {
         undefined,
     )
 
+    const [postPayload, setPostPayload] = useState(deconstructPayload(encryptedText, null))
```
Comment (SunriseFox) [inline src/components/InjectedComponents/DecryptedPost.tsx]: if like this, `deconstructPayload(encryptedText, null)` will still have to be called every re-render (as it is an expression, its value needs to be evaluated before becomes an argument)... should be `() =>deconstructPayload(encryptedText, null)` so that react will detect the need of evaluating it.

**Comment by neruthes** [comment]
Note:

I edited OP to connect this with #759.
