### PR TITLE
fix: only dhedge in plugin list page

### LINKED ISSUE #3567: [Bug] Only Dhedge in plugin list page
### How to reproduce?
Screen Shot 2021-07-02 at 16 46 31
### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

### PR DESCRIPTION
**Pull request by lelenei**
closes #3567

### CODE REVIEW

**Review by guanbinrui — APPROVED** [review]

File: packages/maskbook/src/extension/options-page/DashboardRouters/Plugins.tsx [hunk 1]
```diff
@@ -6,6 +6,7 @@ import PluginCard from '../DashboardComponents/PluginCard'
 import DashboardRouterContainer from './Container'
 import { PluginUI } from '../../../plugins/PluginUI'
 import { PluginScope } from '../../../plugins/types'
+import { useActivatedPluginsSNSAdaptor } from '@masknet/plugin-infra'
```
Comment (Jack-Works) [inline packages/maskbook/src/extension/options-page/DashboardRouters/Plugins.tsx:9]: Actually, this only lists the "enabled" plugins, but since we don't have that functionality yet, I will handle this in #3066
