### PR TITLE
fix(trending): shows available data/trade providers only

### LINKED ISSUE #2904: [Bug] Only show available data provider of the searched keyword
### How to reproduce?

The `test` keyword is only available on Uniswap Info. But it's possible to switch to another data provider.

image

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

### PR DESCRIPTION
**Pull request by UncleBill**
closes #2904

image

image

### CODE REVIEW

File: packages/maskbook/src/plugins/Trader/UI/trending/TrendingViewDeck.tsx [hunk 1]
```diff
@@ -204,7 +204,10 @@ export function TrendingViewDeck(props: TrendingViewDeckProps) {
     )
     //#endregion
 
-    const dataProviderOptions = getEnumAsArray(DataProvider)
+    const isTestForUniswap = coin.symbol === 'test'
```
Comment (UncleBill) [inline packages/maskbook/src/plugins/Trader/UI/trending/TrendingViewDeck.tsx:207]: `coin.symbol` is always lowercase.

File: packages/maskbook/src/plugins/Trader/UI/trending/TrendingViewDeck.tsx [hunk 2]
```diff
@@ -204,7 +206,8 @@ export function TrendingViewDeck(props: TrendingViewDeckProps) {
     )
     //#endregion
 
-    const dataProviderOptions = getEnumAsArray(DataProvider)
+    const dataProviderOptions = getEnumAsArray(DataProvider).filter((option) => dataProviders.includes(option.value))
+    console.log('dataProviderOptions', dataProviderOptions, dataProviders, getEnumAsArray(DataProvider))
```
Comment (guanbinrui) [inline packages/maskbook/src/plugins/Trader/UI/trending/TrendingViewDeck.tsx:210]:
```suggestion
```

**Review by guanbinrui — APPROVED** [review]

**Review by Jack-Works — APPROVED** [review]
