### PR TITLE
fix: dashboard crash

### LINKED ISSUE #9953: [Crash] TypeError: Cannot destructure property 'currentVisitingProfile' of '(0 , _dom_useSNSAdaptorContext_js__WEBPACK_IMPORTED_MODULE_1__.B)(...)' as it is undefined.
I just opened welcome page, then Mask reports an error.
Version: Develop 1358c90

> Cannot destructure property 'currentVisitingProfile' of '(0 , _dom_useSNSAdaptorContext_js__WEBPACK_IMPORTED_MODULE_1__.B)(...)' as it is undefined.

Error stack:

<pre>TypeError: Cannot destructure property 'currentVisitingProfile' of '(0 , _dom_useSNSAdaptorContext_js__WEBPACK_IMPORTED_MODULE_1__.B)(...)' as it is undefined.
  at useCurrentVisitingIdentity (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/1663.js:87:13)
  at useCurrentVisitingUser (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.5634.js:63:81)
  at AnimatePic (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.5634.js:841:21)
  at Jf (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:425:143)
  at Fk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:586:338)
  at Bk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:572:321)
  at Ak (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:570:423)
  at ef (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:570:264)
  at ff (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:565:94)
  at pf (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:563:263)
  at J (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/5777.js:2195:206)
  at R (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/5777.js:2196:128)
  at queue.<computed> (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/polyfill/ecmascript.js:2773:7)
  at run (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/polyfill/ecmascript.js:2747:5)
  at MessagePort.eventListener (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/polyfill/ecmascript.js:2758:3)</pre>

### PR DESCRIPTION
**Pull request by guanbinrui**
## Description

Closes #9953
Closes [MF-4393](https://mask.atlassian.net/browse/MF-4393) .

## Type of change

- [ ] Documentation
- [ ] Code refactoring (Restructuring existing code w/o changing its observable behavior)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (a fix or feature that would make something no longer possible to do/require old user must upgrade their Mask Network to this new version)

## Checklist

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
  - [ ] I have removed all in development `console.log`s
  - [ ] I have removed all commented code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have read [Internationalization Guide](https://github.com/DimensionDev/Maskbook/blob/develop/docs/i18n-guide.md) and moved text fields to the i18n JSON file.

If this PR depends on external APIs:

- [ ] I have configured those APIs with CORS headers to let extension requests get passed. 
  - chrome extension: `chrome-extension://[id]`
  - firefox extension: `moz-extension://[id]`
- [ ] I have delegated all web requests to the background service via the internal RPC bridge.

[MF-4393]: https://mask.atlassian.net/browse/MF-4393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: packages/mask/src/social-network/ui.ts [hunk 1]
```diff
@@ -158,6 +158,8 @@ export async function activateSocialNetworkUIInner(ui_deferred: SocialNetworkUI.
         })
     }
 
+    console.log('DEBUG: SNSAdaptorContextRef')
+
```
Comment (guanbinrui) [inline packages/mask/src/social-network/ui.ts]:
```suggestion
```

**Review by Jack-Works — APPROVED** [review]
