### PR TITLE
fix: text input of 'Find Your Username' dialog is disabled after clea…

### LINKED ISSUE #3098: [Bug] Text input of "Find Your Username" dialog is disabled after clearing the text
## Bug Info
During new persona creation, text input is disabled after clearing the text, this would block the new persona creation flow

### How to reproduce?

1. Create a new persona
2. Click Twitter.com to connect the persona to a Twitter account
3. When the "Find Your Username" dialog appears, click the username text input, then clear the texts.

### What happened?
The text input becomes disabled after clearing the texts, the user could not input anything or proceed the account connection flow.
Snipaste_2021-05-07_11-23-39

### What should happen?
The text input should always be editable.

### Mask Version:

- [x] (Browser) Installed from the extension store (version: 1.31.9)
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

### PR DESCRIPTION
**Pull request by lelenei**
…ring the text

closes #3098

### CODE REVIEW

File: packages/maskbook/src/components/InjectedComponents/SetupGuide.tsx [hunk 1]
```diff
@@ -412,8 +411,7 @@ function FindUsername({ username, onConnect, onDone, onClose, onUsernameChange =
                                 <IconButton
                                     className={findUsernameClasses.button}
                                     // @ts-expect-error https://github.com/mui-org/material-ui/pull/26064
-                                    color={username ? 'primary' : 'default'}
-                                    disabled={!username}>
```
Comment (guanbinrui) [inline packages/maskbook/src/components/InjectedComponents/SetupGuide.tsx:416]: I think this is required, right? The button should not react to clicks if the username absent.

**Review by jk234ert — APPROVED** [review]
