### PR TITLE
fix: dhedge plugin was involved in incorrect context

### LINKED ISSUE #3509: [Bug] Dhedge plugin was involved in incorrect context
### How to reproduce?

1. Go to twitter "https://twitter.com/PancakeSwap/status/1408054897996566535"
2. Switch chain to "BSC" or "Polygon"

### What happened?
Dhedge plugin was activated.
WeChat5ed69e2da4a016f08930d20f9c4348d3

### What should happen?

Shouldn't be involved.

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

### PR DESCRIPTION
**Pull request by lelenei**
closes #3509

### CODE REVIEW

File: packages/maskbook/src/plugins/dHEDGE/define.tsx [hunk 1]
```diff
@@ -57,6 +59,12 @@ export const DHedgePluginDefine: PluginConfig = {
 function Renderer(props: React.PropsWithChildren<{ url: string }>) {
     const DHEDGE_POOL_PATTERN = usePoolUrlPattern()
     const address = props.url.match(DHEDGE_POOL_PATTERN) || []
+
+    //#region check pool
+    const { value: pool, error, loading, retry } = useFetchPool(address[1])
```
Comment (guanbinrui) [inline packages/maskbook/src/plugins/dHEDGE/define.tsx:64]: Found the same logic in the `<PoolView />`, why not do the validation in that component?

**Review by Jack-Works — APPROVED** [review]

**Review by guanbinrui — APPROVED** [review]

**Comment by Tedko** [comment]
lets deliver this fix early this week. been reported by users several times cc @guanbinrui
