### PR TITLE
fix: missing border of TradeFooter

### LINKED ISSUE #3044: [Bug] The footnote border is gone
### How to reproduce?

image

The `<Footnote />` border is gone in the `<SeachResultView />`.

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [x] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

### PR DESCRIPTION
**Pull request by UncleBill**
closes #3044

image

### CODE REVIEW

**Review by Jack-Works — DISMISSED** [review]

File: packages/maskbook/src/plugins/Trader/UI/trader/TradeFooter.tsx [hunk 1]
```diff
@@ -72,7 +75,7 @@ export const TradeFooter: FC<TradeFooterProps> = ({
         ? getEnumAsArray(TradeProvider).filter((x) => tradeProviders.includes(x.value))
         : []
     return (
-        <CardActions className={classes.footer}>
+        <CardActions className={classNames(classes.footer, className)}>
```
Comment (guanbinrui) [inline packages/maskbook/src/plugins/Trader/UI/trader/TradeFooter.tsx:78]: Refactor it by using `useStylesExtends`.

**Review by guanbinrui — APPROVED** [review]

**Review by Jack-Works — APPROVED** [review]
