### PR TITLE
fixup! fix: treat inline svg code as locale resource (#7273)

### LINKED ISSUE #7270: /^data|blob:|\w+-extension:\/\//.test(url)
```suggestion
    return /^data|blob:|\w+-extension:\/\//.test(url)
```

_Originally posted by @guanbinrui in https://github.com/DimensionDev/Maskbook/pull/7240#discussion_r958473106_

### PR DESCRIPTION
**Pull request by UncleBill**
closes https://github.com/DimensionDev/Maskbook/issues/7270

### CODE REVIEW

File: packages/shared/src/UI/components/Image/loadImage.ts [hunk 1]
```diff
@@ -21,7 +25,7 @@ export async function loadImage(url: string) {
         img.addEventListener('error', onerror)
         img.src = url
     }).catch(async () => {
-        const response = await fetch(url, {
+        const response = await globalThis.r2d2Fetch(url, {
```
Comment (guanbinrui) [inline packages/shared/src/UI/components/Image/loadImage.ts]: The `fetch` is equal to `globalThis.r2d2Fetch`.

**Review by Jack-Works — APPROVED** [review]

**Review by guanbinrui — APPROVED** [review]
