### PR TITLE
fix: change wallet dialog should be closed automatically after changi…

### LINKED ISSUE #5059: [Bug] Change wallet dialog should be closed automatically after changing complete in mask dashboard
### How to reproduce?

image

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [x] Build of version/commit hash: /dev

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

### PR DESCRIPTION
**Pull request by lelenei**
…ng complete in mask dashboard

closes #5059

### CODE REVIEW

**Review by Jack-Works — DISMISSED** [review]

**Comment by AinuX** [comment]
Checked

File: packages/mask/src/plugins/Wallet/SNSAdaptor/SelectProviderDialog/index.tsx [hunk 1]
```diff
@@ -46,7 +46,7 @@ export function SelectProviderDialog(props: SelectProviderDialogProps) {
 
     const networks = getRegisteredWeb3Networks()
     const providers = getRegisteredWeb3Providers()
-
+    const isDashboard = location.href.includes('dashboard.html')
```
Comment (zhouhanseng) [inline packages/mask/src/plugins/Wallet/SNSAdaptor/SelectProviderDialog/index.tsx:49]: Would you mind to encapsulate `checkDashboard()` at `@masknet/shared`?
