### PR TITLE
Release 1.21.3

### LINKED ISSUE #2029: [Crash] TypeError: Cannot read property 'currency' of undefined
Screen Shot 2020-12-05 at 05 09 04

I was ___trying to swap $ to some $ at search page_____, then Maskbook report an error.

> Cannot read property 'currency' of undefined

Error stack:
<pre>TypeError: Cannot read property 'currency' of undefined
    at Function.swapCallParameters (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.uniswap.chunk.js:1439:37)
    at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:14772:39
    at Object.Yh [as useMemo] (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:179:444)
    at push.1048.exports.useMemo (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react.chunk.js:76:414)
    at useSwapParameters (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:14767:36)
    at useTradeCallback_useTradeCallback (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:14816:29)
    at trader_useTradeCallback_useTradeCallback (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:14900:21)
    at Trader (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:15536:61)
    at wh (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:167:137)
    at gi (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:191:158)</pre>

## Build information:

- Version: 1.20.1
- NODE_ENV: production
- STORYBOOK: false
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: undefined
- resolution: desktop
- BUILD_DATE: 2020-12-03T16:27:22.741Z
- VERSION: v1.20.0-7-gfffb121b

## Git (*):

fffb121b (released) on tag "v1.20.1"
git@github.com:DimensionDev/Maskbook.git

### LINKED ISSUE #2033: [Bug] $ytrump Price info not correct
image

image
### System

- [ ] Windows

  - OS Version:

- [ ] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [ ] Chrome

  - Maskbook Version:
  - Browser Version:

- [ ] Firefox

  - Maskbook Version:
  - Browser Version:

- [ ] Android

  - Maskbook Version:
  - Android Version:

- [ ] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook?
  - [ ] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

/_What happened?_/
image

### LINKED ISSUE #2048: [Bug] Reduce uniswap pair queries with thegraph API
### System

- [ ] Windows

  - OS Version:

- [x] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Chrome

  - Maskbook Version:
  - Browser Version:

- [x] Firefox

  - Maskbook Version:
  - Browser Version:

- [ ] Android

  - Maskbook Version:
  - Android Version:

- [ ] iOS
  - Maskbook Version:
  - iOS Version:

### Build Variant

- Where do you get Maskbook?
  - [ ] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

## Bug Info

https://thegraph.com/explorer/subgraph/uniswap/uniswap-v2

### Actual Behavior

/_What happened?_/

### PR DESCRIPTION
**Pull request by guanbinrui**
+ [ ] close #2029
+ [x] close #2033
+ [x] close #2048

### CODE REVIEW

File: packages/maskbook/src/plugins/Trader/apis/uniswap/index.ts [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+        }[]
+    }
+}
+
+export async function queryPairs(ids: string[]) {
+    const response = await fetch(THEGRAPH_UNISWAP_V2, {
+        method: 'POST',
+        mode: 'cors',
+        body: JSON.stringify({
+            query: `
```
Comment (Jack-Works) [inline packages/maskbook/src/plugins/Trader/apis/uniswap/index.ts:18]: GraphQL?

Comment (guanbinrui) [reply packages/maskbook/src/plugins/Trader/apis/uniswap/index.ts:18]: yep

**Review by Jack-Works — APPROVED** [review]
